[font]
family = "JetBrainsMono Nerd Font"
size = 14

codepoint_map = [
  { range = "U+AC00-U+D7A3", family = "D2Coding" },
  { range = "U+3130-U+318F", family = "D2Coding" },
]

[ghostty]
shader = "cursor_tail.glsl"
icon_screen = "#16161d"
