[meta]
name = "alma"
group = "VA-11 Hall-A"
order = 45
ansi_source = "Belafonte Night + Glitch City"
booru = "alma_armas"
signature = ["cursor", "ansi12", "ansi9"]

[colors]
background = "#1e160d"
foreground = "#f6dfc6"
cursor = "#eaa549"
selection_background = "#483a3f"
ansi = [
  "#2b2218",
  "#fc7c34",
  "#c3a95f",
  "#f4ae51",
  "#6fad92",
  "#e39351",
  "#9aba81",
  "#d4c4b5",

  "#827568",
  "#ffac9c",
  "#e4ca7d",
  "#ffd6a0",
  "#8fc9e4",
  "#ffafce",
  "#bbdca0",
  "#ffebd6",
]
