[meta]
name = "alma"
group = "VA-11 Hall-A"
order = 45
ansi_source = "Belafonte Night + Glitch City"
signature = ["cursor", "ansi12", "ansi9"]

[colors]
background = "#1e160d"
foreground = "#f6dfc6"
cursor = "#eaa549"
selection_background = "#483a3f"
ansi = [
  "#2b2218",
  "#fc7c34",
  "#c3a95f",
  "#f4ae51",
  "#6fad92",
  "#e39351",
  "#9aba81",
  "#d4c4b5",

  "#827568",
  "#ee6a52",
  "#e4ca7d",
  "#ffd6a0",
  "#74a2b8",
  "#ffb778",
  "#bbdca0",
  "#ffebd6",
]
