[meta]
name = "anko"
group = "Call of the Night"
order = 65
ansi_source = "Arthur"
signature = ["cursor", "ansi4", "ansi2"]

[colors]
background = "#201511"
foreground = "#fddcd0"
cursor = "#ef6c33"
selection_background = "#473c32"
ansi = [
  "#2d211c",
  "#f67d6a",
  "#86af80",
  "#f6ab68",
  "#6495ed",
  "#d59964",
  "#c3a5db",
  "#d8c2bb",

  "#85736d",
  "#ffad93",
  "#f9c50d",
  "#ffd4bc",
  "#bcbbfb",
  "#ffb877",
  "#e5c6fe",
  "#ffe9e2",
]
