[meta]
name = "asuka"
group = "Evangelion"
order = 9
ansi_source = "GitLab Dark"
signature = ["cursor", "ansi11", "ansi4"]

[colors]
background = "#211513"
foreground = "#fddbd5"
cursor = "#e8442c"
selection_background = "#5b322e"
ansi = [
  "#2e211e",
  "#f47e6b",
  "#b9ae2f",
  "#ffa765",
  "#7fb6ed",
  "#f68393",
  "#7bc175",
  "#d8c2be",

  "#857370",
  "#fdada0",
  "#d6cf77",
  "#e9be74",
  "#d5b2ff",
  "#ffb2ba",
  "#a6e18e",
  "#ffe9e5",
]
