[meta]
name = "azusa"
group = "K-On!"
order = 86
ansi_source = "Retro Legends"
signature = ["cursor", "ansi9", "foreground"]

[colors]
background = "#141117"
foreground = "#eef2ee"
cursor = "#45eb45"
selection_background = "#322b38"
ansi = [
  "#262626",
  "#de5454",
  "#45eb45",
  "#f7bf2b",
  "#4066f2",
  "#bf4cf2",
  "#40d9e6",
  "#bfe6bf",

  "#4c594c",
  "#ff6666",
  "#59ff59",
  "#ffd933",
  "#4c80ff",
  "#e666ff",
  "#59e6ff",
  "#f2fff2",
]
