[meta]
name = "azusa"
group = "K-On!"
order = 86
ansi_source = "Retro Legends"
signature = ["cursor", "ansi9", "foreground"]

[colors]
background = "#131912"
foreground = "#dfe3e0"
cursor = "#81e473"
selection_background = "#423b48"
ansi = [
  "#1f251d",
  "#e08e00",
  "#5fc055",
  "#c4c033",
  "#00afd5",
  "#68a7ff",
  "#30c5ac",
  "#c2c8bc",

  "#73796e",
  "#ffaba7",
  "#7fe273",
  "#dbe650",
  "#00d2fb",
  "#ffb4a9",
  "#58e7d4",
  "#e6f1de",
]
