[meta]
name = "battler"
group = "Umineko"
order = 77
ansi_source = "Deep"
signature = ["cursor", "ansi4", "ansi11"]

[colors]
background = "#201513"
foreground = "#fddbd6"
cursor = "#fb0007"
selection_background = "#5c322e"
ansi = [
  "#2e211f",
  "#ff7765",
  "#caa900",
  "#ffa92d",
  "#5665ff",
  "#f879c9",
  "#83c073",
  "#d8c2be",

  "#857370",
  "#ffac9f",
  "#f0c900",
  "#fedc2b",
  "#ebaafa",
  "#ffaedc",
  "#a9e095",
  "#ffe9e6",
]
