[meta]
name = "battler"
group = "Umineko"
order = 77
ansi_source = "Deep"
booru = "ushiromiya_battler"
signature = ["cursor", "ansi4", "ansi11"]

[colors]
background = "#201513"
foreground = "#fddbd6"
cursor = "#ee6554"
selection_background = "#5c322e"
ansi = [
  "#2e211f",
  "#ff7765",
  "#bfae10",
  "#f7af1f",
  "#8e98ff",
  "#f879c9",
  "#83c073",
  "#d8c2be",

  "#857370",
  "#ffac9f",
  "#cbd837",
  "#fddc2a",
  "#cdb8ff",
  "#ffaedc",
  "#a9e095",
  "#ffe9e6",
]
