[meta]
name = "beatrice"
group = "Umineko"
order = 78
ansi_source = "Batman + Truth"
signature = ["cursor", "foreground", "ansi9"]

[colors]
background = "#19180d"
foreground = "#f4e1b0"
cursor = "#e1d61b"
selection_background = "#473d12"
ansi = [
  "#252418",
  "#ada400",
  "#b7ae38",
  "#c2c200",
  "#69ad9e",
  "#de9382",
  "#8cbc8f",
  "#cbc7b5",

  "#7a7768",
  "#cbc462",
  "#dacf5f",
  "#ede061",
  "#89cebe",
  "#ffb4a4",
  "#addeaf",
  "#f4efd2",
]
