[meta]
name = "bernkastel"
group = "Umineko"
order = 79
ansi_source = "Challenger Deep"
signature = ["cursor", "ansi5", "ansi1"]

[colors]
background = "#13181e"
foreground = "#dbe3f1"
cursor = "#65b2ff"
selection_background = "#3e3a58"
ansi = [
  "#1f242a",
  "#ff5458",
  "#00bec0",
  "#f5a4c2",
  "#57a5f1",
  "#906cff",
  "#30c0e0",
  "#c3c7cf",

  "#73777f",
  "#faa2ff",
  "#00e4da",
  "#b5eabd",
  "#87c9f3",
  "#c8bfff",
  "#87dfea",
  "#e6eefd",
]
