[meta]
name = "bihyung"
group = "Eternal Return"
order = 102
ansi_source = "Pierre Dark + Lumia"
signature = ["cursor", "ansi2", "ansi13"]

[colors]
background = "#18180d"
foreground = "#e7e3c8"
cursor = "#f4f11f"
selection_background = "#5b3234"
ansi = [
  "#252419",
  "#f78017",
  "#74d6b0",
  "#c4c100",
  "#00b4a5",
  "#fd8363",
  "#56c494",
  "#cac7b6",

  "#797869",
  "#ffaf7d",
  "#a5d99e",
  "#e3e27a",
  "#5dd4c5",
  "#cf7db6",
  "#8ae3b8",
  "#f2efd3",
]
