[meta]
name = "bocchi"
group = "Bocchi the Rock!"
order = 29
ansi_source = "Sakura + Kessoku"
signature = ["cursor", "ansi4", "ansi9"]

[colors]
background = "#201517"
foreground = "#fadbe1"
cursor = "#feabc0"
selection_background = "#51344e"
ansi = [
  "#2c2123",
  "#fd729f",
  "#daa200",
  "#fea49a",
  "#86a1d3",
  "#f979c8",
  "#abb772",
  "#d6c2c5",

  "#847376",
  "#ffa7ca",
  "#ffc30f",
  "#ffd3ce",
  "#e5abff",
  "#ffaeda",
  "#ccd890",
  "#ffe8ec",
]
