[meta]
name = "cirno"
group = "Touhou Project"
order = 93
ansi_source = "Forest Blue"
booru = "cirno"
signature = ["cursor", "ansi6", "ansi5"]

[colors]
background = "#12181d"
foreground = "#d8e4ef"
cursor = "#a5d8fa"
selection_background = "#2e3e5a"
ansi = [
  "#1e2529",
  "#ed7ca3",
  "#73b997",
  "#b2c45b",
  "#68abb8",
  "#b597ed",
  "#7ab7e9",
  "#c1c7ce",

  "#71787e",
  "#ffa8c4",
  "#93dbb7",
  "#cde462",
  "#6bcfe0",
  "#b8c3ff",
  "#a4d8ff",
  "#e3f0fa",
]
