[meta]
name = "danger"
group = "Warning"
order = 17
role = "warning"
ansi_source = "Mirage"

[colors]
background = "#2a0e0e"
foreground = "#a6b2c0"
cursor = "#ff4d4d"
selection_background = "#4d1c1c"
ansi = [
  "#011627",
  "#ff9999",
  "#85cc95",
  "#ffd700",
  "#7fb5ff",
  "#ddb3ff",
  "#21c7a8",
  "#ffffff",

  "#575656",
  "#ff9999",
  "#85cc95",
  "#ffd700",
  "#7fb5ff",
  "#ddb3ff",
  "#85cc95",
  "#ffffff",
]
