[meta]
name = "dekomori"
group = "Chuunibyou"
order = 100
ansi_source = "Cobalt2 + Delusion"
signature = ["cursor", "ansi12", "ansi5"]

[colors]
background = "#1a180d"
foreground = "#ece2c6"
cursor = "#f0cc09"
selection_background = "#264058"
ansi = [
  "#272418",
  "#f58209",
  "#95b821",
  "#d6bb00",
  "#00b2bc",
  "#ff005d",
  "#64c386",
  "#cdc6b4",

  "#7c7767",
  "#ffaf75",
  "#b5da43",
  "#ffdb37",
  "#6b6bff",
  "#ffb3ad",
  "#7de5b8",
  "#f8edd1",
]
