[meta]
name = "determination"
group = "Undertale"
order = 61
ansi_source = "CGA + Determination"
signature = ["cursor", "ansi11", "ansi4"]

[colors]
background = "#211513"
foreground = "#fddbd5"
cursor = "#ed6653"
selection_background = "#413f15"
ansi = [
  "#2e211f",
  "#ff7766",
  "#3dc886",
  "#debb5d",
  "#9496ff",
  "#ff78b4",
  "#7ec176",
  "#d8c2be",

  "#857370",
  "#ffaba3",
  "#4bed9f",
  "#e4e43b",
  "#d2b8ff",
  "#ffb0cf",
  "#92e689",
  "#ffe9e6",
]
