[meta]
name = "determination"
group = "Undertale"
order = 61
ansi_source = "CGA + Determination"
signature = ["cursor", "ansi11", "ansi4"]

[colors]
background = "#211513"
foreground = "#fddbd5"
cursor = "#ff0000"
selection_background = "#413f15"
ansi = [
  "#2e211f",
  "#ff7766",
  "#caa900",
  "#ffa67c",
  "#5555ff",
  "#ff78b4",
  "#8dbe6a",
  "#d8c2be",

  "#857370",
  "#ffaba3",
  "#eeca00",
  "#ffff55",
  "#f4a5ff",
  "#ffb0cf",
  "#a4e37b",
  "#ffe9e6",
]
