[meta]
name = "dorothy"
group = "VA-11 Hall-A"
order = 44
ansi_source = "Cyberpunk + Glitch City"
booru = "dorothy_haze"
signature = ["cursor", "ansi4", "ansi5"]

[colors]
background = "#201515"
foreground = "#fbdbdc"
cursor = "#ed6376"
selection_background = "#573243"
ansi = [
  "#2d2021",
  "#ff728e",
  "#bead00",
  "#feaa2f",
  "#00ace6",
  "#d289f2",
  "#b4a7f3",
  "#d7c1c2",

  "#857374",
  "#ffaab6",
  "#d5d21f",
  "#ffd6a9",
  "#babbff",
  "#fface7",
  "#d2ccff",
  "#ffe9e9",
]
