[meta]
name = "flandre"
group = "Touhou Project"
order = 96
ansi_source = "Molokai"
signature = ["cursor", "ansi11", "ansi12"]

[colors]
background = "#201514"
foreground = "#fcdbd9"
cursor = "#e60033"
selection_background = "#59323e"
ansi = [
  "#2d2120",
  "#ff7389",
  "#d8a300",
  "#f5ad4b",
  "#b38df7",
  "#ed7de0",
  "#aea8fa",
  "#d7c1c0",

  "#857372",
  "#ffa9b8",
  "#ffc330",
  "#fff26d",
  "#00afff",
  "#ffaaf7",
  "#d1ccff",
  "#ffe9e8",
]
