[meta]
name = "fox"
group = "Persona 5"
order = 52
ansi_source = "Nord"
signature = ["cursor", "foreground", "ansi1"]

[colors]
background = "#12181d"
foreground = "#eceff4"
cursor = "#05a9ee"
selection_background = "#353e4f"
ansi = [
  "#1e242a",
  "#bf616a",
  "#75b8a5",
  "#9cc795",
  "#79a5ca",
  "#ab9ed5",
  "#7eb9d2",
  "#c1c7ce",

  "#71787e",
  "#e6acfa",
  "#95d9c6",
  "#bce9b4",
  "#9ac6ec",
  "#ccbff7",
  "#9adceb",
  "#e3effb",
]
