[meta]
name = "glitch"
group = "Doki Doki Literature Club"
order = 76
ansi_source = "Neon + DDLC"
signature = ["cursor", "ansi10", "ansi12"]

[colors]
background = "#1d151b"
foreground = "#f3dcea"
cursor = "#d767c5"
selection_background = "#443858"
ansi = [
  "#2a2127",
  "#fd729d",
  "#94bd47",
  "#ffa75f",
  "#9c95ff",
  "#f07cdb",
  "#6cb5ff",
  "#d2c2cb",

  "#80747b",
  "#ffa9bd",
  "#70e47e",
  "#ffd5b6",
  "#a4c1ff",
  "#ffabee",
  "#add6fe",
  "#ffe7f5",
]
