[meta]
name = "gojo"
group = "Jujutsu Kaisen"
order = 102
ansi_source = "Horizon + Jujutsu"
booru = "gojou_satoru"
signature = ["cursor", "foreground", "ansi13"]

[colors]
background = "#11191c"
foreground = "#e3e2e7"
cursor = "#7cc1d6"
selection_background = "#383b5b"
ansi = [
  "#1d2528",
  "#fb70a4",
  "#4cbf8e",
  "#c5be73",
  "#79a4cf",
  "#a3a0d4",
  "#31c2d0",
  "#bfc8cb",

  "#70787c",
  "#ffa7c3",
  "#5de3a9",
  "#e7df91",
  "#62ccf9",
  "#d7bcf3",
  "#6ce2f0",
  "#e0f1f7",
]
