[meta]
name = "hachiman"
group = "Oregairu"
order = 109
ansi_source = "Smyck + Service Club"
booru = "hikigaya_hachiman"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#17171f"
foreground = "#e2e1f2"
cursor = "#6e6e7d"
selection_background = "#15434c"
ansi = [
  "#23232b",
  "#fb72a5",
  "#4bbf8d",
  "#d6ba52",
  "#70a8c4",
  "#b599e1",
  "#86b5e0",
  "#c7c5d0",

  "#777680",
  "#fbaac4",
  "#58e4a9",
  "#f4dab7",
  "#99c5f5",
  "#dcb8ff",
  "#8bdcff",
  "#eeecfe",
]
