[meta]
name = "hinamizawa"
group = "Higurashi"
order = 71
ansi_source = "Red Sands"
signature = ["cursor", "ansi2", "ansi3"]

[colors]
background = "#201512"
foreground = "#fddbd3"
cursor = "#ec6745"
selection_background = "#5c3230"
ansi = [
  "#2e211d",
  "#ff7855",
  "#63bf52",
  "#ebb308",
  "#cf7ff8",
  "#ff79af",
  "#8abf66",
  "#d8c2bc",

  "#85736f",
  "#ffac9d",
  "#ecca00",
  "#ffd5ae",
  "#d2b3ff",
  "#ffb0cc",
  "#a4e37b",
  "#ffe9e4",
]
