[meta]
name = "hitagi"
group = "Monogatari"
order = 33
ansi_source = "Duskfox"
signature = ["cursor", "ansi9", "ansi13"]

[colors]
background = "#1e151a"
foreground = "#f5dce8"
cursor = "#b56d9e"
selection_background = "#403956"
ansi = [
  "#2b2127",
  "#f179ad",
  "#d1a360",
  "#f9a88b",
  "#8d9fd9",
  "#c396d0",
  "#98b1e1",
  "#d3c2ca",

  "#81737a",
  "#f083a2",
  "#f5c47e",
  "#ffd3c5",
  "#acbffd",
  "#ccb1ed",
  "#bbd2ff",
  "#ffe8f3",
]
