[meta]
name = "homura"
group = "Madoka Magica"
order = 16
ansi_source = "Monokai Pro Machine"
signature = ["cursor", "foreground", "ansi5"]

[colors]
background = "#1b1428"
foreground = "#f2fffc"
cursor = "#8b5cf6"
selection_background = "#322447"
ansi = [
  "#273136",
  "#ff6d7e",
  "#a2e57b",
  "#ffed72",
  "#ffb270",
  "#baa0f8",
  "#7cd5f1",
  "#f2fffc",

  "#6b7678",
  "#ff6d7e",
  "#a2e57b",
  "#ffed72",
  "#ffb270",
  "#baa0f8",
  "#7cd5f1",
  "#f2fffc",
]
