[meta]
name = "homura"
group = "Madoka Magica"
native = "魔法少女まどか☆マギカ"
order = 8
ansi_source = "Monokai Pro Machine + Magica"

[colors]
background = "#1b1428"
foreground = "#f2fffc"
cursor = "#8b5cf6"
selection_background = "#322447"
ansi = [
  "#2d282f",
  "#ff6d7e",
  "#a2e57b",
  "#ffed72",
  "#ffb270",
  "#baa0f8",
  "#7cd5f1",
  "#f2fffc",

  "#6a6767",
  "#ff6d7e",
  "#a2e57b",
  "#ffed72",
  "#ffb270",
  "#baa0f8",
  "#7cd5f1",
  "#f2fffc",
]
