[meta]
name = "homura"
group = "Madoka Magica"
order = 16
ansi_source = "Monokai Pro Machine"
signature = ["cursor", "foreground", "ansi5"]

[colors]
background = "#19161e"
foreground = "#d8e5e2"
cursor = "#9f79fb"
selection_background = "#453858"
ansi = [
  "#25222b",
  "#f075c8",
  "#00bec0",
  "#ffa67d",
  "#979bdd",
  "#b198ef",
  "#82b4ed",
  "#cac4cf",

  "#7a757f",
  "#ffa5dd",
  "#00e3e4",
  "#ffd4c2",
  "#b9bcf9",
  "#d0bcff",
  "#b2d5ff",
  "#f3eafd",
]
