[meta]
name = "jill"
group = "VA-11 Hall-A"
order = 43
ansi_source = "TokyoNight"
signature = ["cursor", "ansi1", "ansi5"]

[colors]
background = "#15181e"
foreground = "#dee2f2"
cursor = "#7aa2f7"
selection_background = "#333d5b"
ansi = [
  "#21242b",
  "#f9778f",
  "#03c0b0",
  "#f7a6a9",
  "#779ff4",
  "#b695f2",
  "#77b6f1",
  "#c5c6d0",

  "#757780",
  "#faa2ff",
  "#4be2d1",
  "#ffd2d3",
  "#a6c0ff",
  "#c4c0ff",
  "#aed6ff",
  "#eaedfe",
]
