[meta]
name = "joker"
group = "Persona 5"
order = 49
ansi_source = "Red Alert + Phantom"
signature = ["cursor", "foreground", "ansi9"]

[colors]
background = "#201513"
foreground = "#f2eef2"
cursor = "#d81818"
selection_background = "#5c3232"
ansi = [
  "#2e211f",
  "#ff7767",
  "#c6aa20",
  "#e5b36c",
  "#b88bf3",
  "#ff78b1",
  "#9dba76",
  "#d8c2be",

  "#857370",
  "#ff3b3b",
  "#f0c83f",
  "#ffd79d",
  "#d3b3ff",
  "#f7b3d3",
  "#bcdb9e",
  "#ffe9e6",
]
