[meta]
name = "jupiter"
group = "Sailor Moon"
order = 40
ansi_source = "Everforest Dark Hard + Senshi"
booru = "sailor_jupiter"
signature = ["cursor", "ansi1", "ansi11"]

[colors]
background = "#131913"
foreground = "#d9e6d5"
cursor = "#36a455"
selection_background = "#4d3743"
ansi = [
  "#1f251e",
  "#eb8284",
  "#92b57d",
  "#c0bf76",
  "#6cad96",
  "#da966d",
  "#83be8e",
  "#c1c9be",

  "#727970",
  "#ffb237",
  "#a3dd5f",
  "#ffd794",
  "#59d2db",
  "#ffb693",
  "#83e5ac",
  "#e4f2e1",
]
