[meta]
name = "kagami"
group = "Lucky☆Star"
order = 26
ansi_source = "Nightfox + Ryouou"
signature = ["cursor", "ansi4", "ansi1"]

[colors]
background = "#19161e"
foreground = "#e8dff1"
cursor = "#9b86c8"
selection_background = "#2f3f55"
ansi = [
  "#25222a",
  "#d58c98",
  "#76b4c9",
  "#f7a895",
  "#9099f2",
  "#b49cd1",
  "#70b8e8",
  "#cbc4cf",

  "#7a757f",
  "#ffa3e6",
  "#97d5eb",
  "#ffd3c8",
  "#b0bff9",
  "#d4bbfe",
  "#a2d8ff",
  "#f4eafd",
]
