[meta]
name = "kagami"
group = "Lucky☆Star"
order = 26
ansi_source = "Nightfox"
signature = ["cursor", "ansi4", "ansi9"]

[colors]
background = "#1a161d"
foreground = "#ebdef0"
cursor = "#a782c7"
selection_background = "#413957"
ansi = [
  "#27222a",
  "#ec78c4",
  "#78b3cb",
  "#f6a990",
  "#719cd6",
  "#bd93f1",
  "#75b7ea",
  "#cdc4ce",

  "#7c757e",
  "#d16983",
  "#99d5ee",
  "#ffd3c6",
  "#b4bdfa",
  "#d8bafc",
  "#a8d7ff",
  "#f7e9fc",
]
