[meta]
name = "kagami"
group = "Lucky☆Star"
order = 26
ansi_source = "Nightfox + Ryouou"
booru = "hiiragi_kagami"
signature = ["cursor", "ansi4", "selection"]

[colors]
background = "#19161e"
foreground = "#e8dff1"
cursor = "#8974b5"
selection_background = "#45282d"
ansi = [
  "#25222a",
  "#d58c98",
  "#81b89c",
  "#efaf7f",
  "#9099f2",
  "#b49cd1",
  "#70b8e8",
  "#cbc4cf",

  "#7a757f",
  "#ffaac5",
  "#a1d9bc",
  "#fad7bd",
  "#b0bff9",
  "#d4bbfe",
  "#a2d8ff",
  "#f4eafd",
]
