[meta]
name = "kagetane"
group = "Black Bullet"
order = 126
ansi_source = "Patina Dark + Varanium"
booru = "hiruko_kagetane"
signature = ["cursor", "foreground", "selection"]

[colors]
background = "#201515"
foreground = "#e2e2ec"
cursor = "#a24a4e"
selection_background = "#4f4258"
ansi = [
  "#2d2120",
  "#e1888c",
  "#b4ae5d",
  "#efae6f",
  "#909fd3",
  "#ba9ace",
  "#8dbd87",
  "#d7c1c1",

  "#857372",
  "#ffabaa",
  "#d6cf7a",
  "#ffd5b0",
  "#b1bff6",
  "#edb5e4",
  "#addfa7",
  "#ffe9e8",
]
