[meta]
name = "kaito"
group = "Vocaloid"
order = 7
ansi_source = "Aardvark Blue + Crypton"
booru = "kaito_(vocaloid)"
signature = ["cursor", "ansi4", "ansi3"]

[meta.booru_sites]
konachan = "kaito"
yande = "kaito"

[colors]
background = "#15171e"
foreground = "#dfe2f2"
cursor = "#5e8df6"
selection_background = "#2f3e5a"
ansi = [
  "#21232b",
  "#ea76d5",
  "#00c0b3",
  "#daba00",
  "#62a1ff",
  "#c18eff",
  "#6bb8ef",
  "#c5c6d0",

  "#757780",
  "#ffa3ea",
  "#00e4d5",
  "#87f2b6",
  "#a2c2f7",
  "#d8b9ff",
  "#9fd9ff",
  "#eaedfe",
]
