[meta]
name = "kaworu"
group = "Evangelion"
order = 11
ansi_source = "Spacegray"
signature = ["cursor", "foreground", "ansi1"]

[colors]
background = "#201515"
foreground = "#d5d9e0"
cursor = "#c9394a"
selection_background = "#423959"
ansi = [
  "#2d2021",
  "#b04b57",
  "#c5a855",
  "#efae7a",
  "#a998ce",
  "#d693ad",
  "#9cba7f",
  "#d7c1c1",

  "#857373",
  "#ffaaaf",
  "#e8c972",
  "#ffd5b6",
  "#cab8f0",
  "#f9b2ce",
  "#bddb9d",
  "#ffe9e8",
]
