[meta]
name = "kirito"
group = "Sword Art Online"
order = 127
ansi_source = "Karasu Night + Aincrad"
booru = "kirito"
signature = ["cursor", "ansi2", "selection"]

[meta.booru_sites]
konachan = "kirigaya_kazuto"

[colors]
background = "#16171f"
foreground = "#e1e1f3"
cursor = "#828bc6"
selection_background = "#2e2f35"
ansi = [
  "#22232b",
  "#dc81cd",
  "#76b8a4",
  "#f8a794",
  "#86a2cf",
  "#a89fd6",
  "#7eb9d2",
  "#c7c5d0",

  "#767680",
  "#ffa3e5",
  "#7cdcd8",
  "#ffd3c6",
  "#a6c2f6",
  "#c8bffb",
  "#9ddaf5",
  "#edecfe",
]
