[meta]
name = "kisara"
group = "Black Bullet"
order = 123
ansi_source = "London Soho Night + Varanium"
booru = "tendou_kisara"
signature = ["cursor", "selection", "ansi4"]

[colors]
background = "#1c151c"
foreground = "#f1ddec"
cursor = "#a478a4"
selection_background = "#753135"
ansi = [
  "#292128",
  "#e1888a",
  "#bdaf48",
  "#f7ac73",
  "#6ea8c2",
  "#ec82cc",
  "#78bbc9",
  "#d0c3cc",

  "#7f747c",
  "#ffa9bd",
  "#ddd174",
  "#fad6bc",
  "#9ac7f2",
  "#ffade2",
  "#9cdbf0",
  "#fce8f8",
]
