[meta]
name = "kita"
group = "Bocchi the Rock!"
order = 32
ansi_source = "Wild Cherry + Kessoku"
signature = ["cursor", "ansi2", "ansi3"]

[colors]
background = "#201513"
foreground = "#fddbd6"
cursor = "#ee6555"
selection_background = "#5a323b"
ansi = [
  "#2e211f",
  "#ff728d",
  "#49c262",
  "#e1b557",
  "#eb76d2",
  "#d792a9",
  "#abb772",
  "#d8c2be",

  "#857370",
  "#ffaca2",
  "#fdc083",
  "#ffd5b2",
  "#c7b7ff",
  "#ffb3b2",
  "#b5d6ec",
  "#ffe9e6",
]
