[meta]
name = "kita"
group = "Bocchi the Rock!"
order = 32
ansi_source = "Wild Cherry + Kessoku"
booru = "kita_ikuyo"
signature = ["cursor", "ansi2", "ansi3"]

[colors]
background = "#201513"
foreground = "#fddbd6"
cursor = "#ee6555"
selection_background = "#5a323b"
ansi = [
  "#2e211f",
  "#ff728d",
  "#49c262",
  "#e1b557",
  "#c287ff",
  "#d692ad",
  "#75c19f",
  "#d8c2be",

  "#857370",
  "#ffaca2",
  "#bbdb90",
  "#ffd5b2",
  "#c7b7ff",
  "#fcb2c3",
  "#b6dbc8",
  "#ffe9e6",
]
