[meta]
name = "kita"
group = "Bocchi the Rock!"
order = 32
ansi_source = "Wild Cherry + Kessoku"
signature = ["cursor", "ansi2", "ansi3"]

[colors]
background = "#241019"
foreground = "#fdeef0"
cursor = "#ff4637"
selection_background = "#4d1e2a"
ansi = [
  "#000507",
  "#d94085",
  "#2ab250",
  "#ffd16f",
  "#883cdc",
  "#ececec",
  "#c1b8b7",
  "#fff8de",

  "#009cc9",
  "#fc4e4a",
  "#f4dca5",
  "#eac066",
  "#308cba",
  "#ae636b",
  "#ff919d",
  "#f2aab2",
]
