[meta]
name = "komachi"
group = "Oregairu"
order = 113
ansi_source = "Catppuccin Frappe + Service Club"
booru = "hikigaya_komachi"
signature = ["cursor", "ansi13", "ansi11"]

[colors]
background = "#16171f"
foreground = "#e0e1f3"
cursor = "#9da9dd"
selection_background = "#4c3935"
ansi = [
  "#22232b",
  "#e184a3",
  "#6fba96",
  "#e3b776",
  "#869fe4",
  "#b99ad0",
  "#7bbacf",
  "#c6c5d0",

  "#767680",
  "#f3aec3",
  "#a0d9bb",
  "#f3dd80",
  "#aec0f3",
  "#cebef7",
  "#9ddbf2",
  "#ecedfe",
]
