[meta]
name = "konata"
group = "Lucky☆Star"
order = 25
ansi_source = "Dark Modern"
signature = ["cursor", "ansi2", "ansi12"]

[colors]
background = "#0f1c30"
foreground = "#cccccc"
cursor = "#4977d6"
selection_background = "#1d3152"
ansi = [
  "#272727",
  "#f74949",
  "#2ea043",
  "#9e6a03",
  "#0078d4",
  "#d01273",
  "#1db4d6",
  "#cccccc",

  "#5d5d5d",
  "#dc5452",
  "#23d18b",
  "#f5f543",
  "#3b8eea",
  "#d670d6",
  "#29b8db",
  "#e5e5e5",
]
