[meta]
name = "konata"
group = "Lucky☆Star"
order = 25
ansi_source = "Dark Modern + Ryouou"
booru = "izumi_konata"
signature = ["cursor", "ansi2", "ansi12"]

[colors]
background = "#13181e"
foreground = "#dae3f1"
cursor = "#598fc4"
selection_background = "#3b3e42"
ansi = [
  "#1f242a",
  "#ff6fa5",
  "#64be79",
  "#b2c365",
  "#63a5e8",
  "#d187ff",
  "#4abcee",
  "#c2c7cf",

  "#73777f",
  "#ffabc6",
  "#4ee4b8",
  "#cce54d",
  "#8fc6ff",
  "#d0bcff",
  "#97daff",
  "#e6effc",
]
