[meta]
name = "kou"
group = "Call of the Night"
order = 63
ansi_source = "Under The Sea"
signature = ["cursor", "ansi5", "ansi9"]

[colors]
background = "#211513"
foreground = "#fddbd5"
cursor = "#d25d4b"
selection_background = "#264242"
ansi = [
  "#2e211e",
  "#ff7668",
  "#c3ab00",
  "#c3b3eb",
  "#9ca757",
  "#1298ff",
  "#daaa24",
  "#d8c2be",

  "#857370",
  "#ff4242",
  "#e9cb00",
  "#e1d7ff",
  "#bbc961",
  "#dab9ff",
  "#ffca3d",
  "#ffe9e5",
]
