[meta]
name = "kumin"
group = "Chuunibyou"
order = 101
ansi_source = "Rose Pine + Delusion"
signature = ["cursor", "ansi4", "ansi1"]

[colors]
background = "#1a161e"
foreground = "#eadef1"
cursor = "#c4a7e7"
selection_background = "#3e3b50"
ansi = [
  "#26222a",
  "#f6789b",
  "#df9d60",
  "#faa69e",
  "#67abb6",
  "#b69ad9",
  "#84b7d6",
  "#ccc4cf",

  "#7b757f",
  "#ffa4e3",
  "#ffbf85",
  "#ffd3ce",
  "#9dc5ee",
  "#d8bafb",
  "#aad8f5",
  "#f5eafc",
]
