[meta]
name = "kumin"
group = "Chuunibyou"
order = 101
ansi_source = "Rose Pine + Delusion"
signature = ["cursor", "ansi4", "ansi1"]

[colors]
background = "#191724"
foreground = "#e0def4"
cursor = "#c4a7e7"
selection_background = "#403d52"
ansi = [
  "#26233a",
  "#eb6f92",
  "#bdcd80",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",

  "#6e6a86",
  "#eb6f92",
  "#bdcd80",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",
]
