[meta]
name = "kumori"
group = "Vocaloid"
order = 3
ansi_source = "MWidzi/inabashell"
signature = ["cursor", "ansi12", "ansi14"]

[colors]
background = "#201516"
foreground = "#fbdbdc"
cursor = "#f5959f"
selection_background = "#493a3f"
ansi = [
  "#2d2021",
  "#ff747d",
  "#c0aa60",
  "#f4ac6e",
  "#ab96d4",
  "#e98b95",
  "#91b3df",
  "#d7c1c2",

  "#857374",
  "#ffaab4",
  "#e4ca7d",
  "#ffd5ad",
  "#c4c9fc",
  "#ffb2ba",
  "#b2dedb",
  "#ffe9e9",
]
