[meta]
name = "kumori"
group = "Vocaloid"
order = 3
ansi_source = "Everblush + Crypton"
signature = ["cursor", "ansi12", "ansi14"]

[colors]
background = "#201516"
foreground = "#fbdbdc"
cursor = "#f5959f"
selection_background = "#383f42"
ansi = [
  "#2d2021",
  "#f17e83",
  "#cea72e",
  "#f4ac6a",
  "#a695e6",
  "#e686c7",
  "#8eb3e6",
  "#d7c1c2",

  "#857374",
  "#ffabad",
  "#f1c74f",
  "#ffd5b3",
  "#b8bdf4",
  "#ffade2",
  "#97deda",
  "#ffe9e9",
]
