[meta]
name = "kurisu"
group = "Steins;Gate"
order = 22
ansi_source = "Duotone Dark"
booru = "makise_kurisu"
signature = ["cursor", "ansi1", "ansi6"]

[colors]
background = "#1f160d"
foreground = "#f9dec8"
cursor = "#e0913f"
selection_background = "#4d3a28"
ansi = [
  "#2c2219",
  "#ff7672",
  "#a3b502",
  "#e2b46f",
  "#999cd2",
  "#e788b0",
  "#84b1ff",
  "#d5c3b6",

  "#837469",
  "#ffad91",
  "#c3d734",
  "#ffd79d",
  "#babdf5",
  "#ffb0cf",
  "#a3d8ff",
  "#ffeadb",
]
