[meta]
name = "kyoko"
group = "Madoka Magica"
native = "魔法少女まどか☆マギカ"
order = 18
ansi_source = "Cursor Dark + Magica"

[colors]
background = "#241014"
foreground = "#d4d4d4"
cursor = "#d63a4a"
selection_background = "#43202a"
ansi = [
  "#242424",
  "#bd4f62",
  "#3fa266",
  "#d2943e",
  "#81a1c1",
  "#b48ead",
  "#88c0d0",
  "#e4e4e4",

  "#4a4a4a",
  "#e14d60",
  "#70b489",
  "#f1b467",
  "#87a6c4",
  "#b48ead",
  "#88c0d0",
  "#e4e4e4",
]
