[meta]
name = "kyoko"
group = "Madoka Magica"
order = 18
ansi_source = "Cursor Dark + Magica"
booru = "sakura_kyouko"
signature = ["cursor", "ansi11", "foreground"]

[colors]
background = "#201515"
foreground = "#e2e2e2"
cursor = "#ee636b"
selection_background = "#59323d"
ansi = [
  "#2d2120",
  "#f67a88",
  "#c1ab2c",
  "#ffa76f",
  "#a898ce",
  "#d493b1",
  "#a5aee3",
  "#d7c1c1",

  "#857372",
  "#ffaaad",
  "#dccd71",
  "#ffd6a7",
  "#c9b9f1",
  "#f8b3d2",
  "#c8cfff",
  "#ffe9e8",
]
