[meta]
name = "kyubey"
group = "Madoka Magica"
order = 21
ansi_source = "Rose Pine Dawn + Magica"
booru = "kyuubee"
signature = ["cursor", "foreground", "ansi3"]

[colors]
background = "#fff8f7"
foreground = "#1f1c39"
cursor = "#b83b64"
selection_background = "#edd0d9"
ansi = [
  "#35292b",
  "#a3556b",
  "#377458",
  "#a66a01",
  "#5b6c9a",
  "#8a5f88",
  "#007098",
  "#514346",

  "#917f82",
  "#91465c",
  "#256449",
  "#a35125",
  "#4d5d8b",
  "#7a5079",
  "#006083",
  "#2c1b1f",
]
