[meta]
name = "lain"
group = "Lain"
order = 42
ansi_source = "IR Black"
signature = ["cursor", "ansi2", "ansi12"]

[colors]
background = "#211513"
foreground = "#fddbd6"
cursor = "#ee6653"
selection_background = "#5c322e"
ansi = [
  "#2e211f",
  "#ff7667",
  "#79bd40",
  "#e1b46e",
  "#ae94d8",
  "#fe78b8",
  "#83b7d7",
  "#d8c2be",

  "#857370",
  "#fdaca4",
  "#ebc960",
  "#ffd799",
  "#99c6ec",
  "#ffafd2",
  "#a4d9f9",
  "#ffe9e6",
]
