[meta]
name = "lain"
group = "Lain"
native = "serial experiments lain"
order = 42
ansi_source = "IR Black"

[colors]
background = "#0b0b0d"
foreground = "#eaeaef"
cursor = "#ff2a00"
selection_background = "#3e3630"
ansi = [
  "#4f4f4f",
  "#fa6c60",
  "#a8ff60",
  "#fffeb7",
  "#96cafe",
  "#fa73fd",
  "#c6c5fe",
  "#efedef",

  "#7b7b7b",
  "#fcb6b0",
  "#cfffab",
  "#ffffcc",
  "#b5dcff",
  "#fb9cfe",
  "#e0e0fe",
  "#ffffff",
]
