[meta]
name = "lambdadelta"
group = "Umineko"
order = 80
ansi_source = "Neon Purple + Truth"
booru = "lambdadelta"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#1f1519"
foreground = "#f7dbe5"
cursor = "#e463a5"
selection_background = "#433859"
ansi = [
  "#2c2125",
  "#f972b0",
  "#bcae00",
  "#c5c036",
  "#00ace6",
  "#f77acb",
  "#6bbae5",
  "#d4c2c7",

  "#827378",
  "#ffa7cd",
  "#decf0b",
  "#ffd5b2",
  "#b1beff",
  "#ffade2",
  "#a4d8f8",
  "#ffe8ef",
]
