[meta]
name = "lambdadelta"
group = "Umineko"
order = 80
ansi_source = "Neon Purple + Truth"
booru = "lambdadelta"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#1f1519"
foreground = "#f7dbe5"
cursor = "#e463a5"
selection_background = "#433859"
ansi = [
  "#2c2125",
  "#fc71a5",
  "#96ba3d",
  "#c5c036",
  "#00ace6",
  "#f77acb",
  "#7bb5ec",
  "#d4c2c7",

  "#827378",
  "#ffa9c4",
  "#decf0a",
  "#f1dcac",
  "#96c7fd",
  "#ffade2",
  "#a4d8f8",
  "#ffe8ef",
]
