[meta]
name = "leafa"
group = "Sword Art Online"
order = 130
ansi_source = "Kanagawa Wave + Aincrad"
booru = "leafa_(sao)"
signature = ["cursor", "ansi11", "selection"]

[meta.booru_sites]
konachan = "leafa"
yande = "leafa"

[colors]
background = "#141911"
foreground = "#dbe6d2"
cursor = "#60aa4f"
selection_background = "#005236"
ansi = [
  "#20251d",
  "#f37c55",
  "#90b681",
  "#c5be73",
  "#53acc1",
  "#a79cd3",
  "#69c296",
  "#c3c8bc",

  "#73796e",
  "#ffab8f",
  "#add98b",
  "#f2dd79",
  "#86cecd",
  "#c8bdf0",
  "#a0dfc0",
  "#e6f1dd",
]
