[meta]
name = "lelouch"
group = "Code Geass"
order = 115
ansi_source = "SilkCircuit Glow + Geass"
booru = "lelouch_lamperouge"
signature = ["selection", "cursor", "ansi1"]

[colors]
background = "#19161e"
foreground = "#e8dff1"
cursor = "#bb7aae"
selection_background = "#562c9d"
ansi = [
  "#25222a",
  "#ff766e",
  "#00bec6",
  "#ffa76d",
  "#7e9cff",
  "#b792ff",
  "#35bbff",
  "#cbc4cf",

  "#7a757f",
  "#ffa6d4",
  "#00e1ef",
  "#ffd4bc",
  "#9ec2ff",
  "#ecb1ff",
  "#a2d8ff",
  "#f4eafd",
]
