[meta]
name = "lelouch"
native_names = ["ルルーシュ・ランペルージ"]
group = "Code Geass"
order = 115
ansi_source = "SilkCircuit Glow + Geass"
booru = "lelouch_vi_britannia"
signature = ["selection", "cursor", "ansi1"]

[meta.booru_sites]
konachan = "lelouch_lamperouge"
yande = "lelouch_lamperouge"
zerochan = "lelouch_lamperouge"

[colors]
background = "#19161e"
foreground = "#e8dff1"
cursor = "#bb7aae"
selection_background = "#562c9d"
ansi = [
  "#25222a",
  "#ff766e",
  "#51bf8f",
  "#ffa76d",
  "#7e9cff",
  "#b792ff",
  "#35bbff",
  "#cbc4cf",

  "#7a757f",
  "#ffaabc",
  "#62e3ab",
  "#fdd5b9",
  "#9ec2ff",
  "#ecb1ff",
  "#a2d8ff",
  "#f4eafd",
]
