[meta]
name = "lucy"
group = "Cyberpunk: Edgerunners"
order = 88
ansi_source = "Mellow"
signature = ["cursor", "foreground", "ansi12"]

[colors]
background = "#1e151a"
foreground = "#eae8f2"
cursor = "#e29eca"
selection_background = "#473757"
ansi = [
  "#2b2127",
  "#d98b95",
  "#b9ac62",
  "#f7a79e",
  "#b594c8",
  "#d491bd",
  "#f691bf",
  "#d3c2ca",

  "#81737a",
  "#fbacb6",
  "#dbcd80",
  "#ffd3cd",
  "#b9aeda",
  "#f5b2de",
  "#ffc0da",
  "#ffe8f3",
]
