[meta]
name = "lucy"
group = "Cyberpunk: Edgerunners"
order = 88
ansi_source = "Mellow"
booru = "lucy_(cyberpunk)"
signature = ["cursor", "foreground", "ansi12"]

[colors]
background = "#1e151a"
foreground = "#e3e1eb"
cursor = "#e29eca"
selection_background = "#473757"
ansi = [
  "#2b2127",
  "#d98b95",
  "#b9ac62",
  "#eeb080",
  "#b594c8",
  "#d491bd",
  "#54bbef",
  "#d3c2ca",

  "#81737a",
  "#fbacb6",
  "#dbcd80",
  "#fad7bf",
  "#c7b9f2",
  "#f5b2de",
  "#abd7f4",
  "#ffe8f3",
]
