[meta]
name = "luka"
group = "Vocaloid"
order = 6
ansi_source = "Rose Pine"
signature = ["cursor", "ansi3", "ansi2"]

[colors]
background = "#1f1517"
foreground = "#f9dbe1"
cursor = "#ffbacc"
selection_background = "#4d3747"
ansi = [
  "#2c2123",
  "#f6789d",
  "#74b3d1",
  "#e6b26a",
  "#8ea0d1",
  "#ca94ca",
  "#83b7d6",
  "#d6c2c5",

  "#837376",
  "#ffa9be",
  "#9dd9b9",
  "#ffd4c0",
  "#aec0f3",
  "#edb4ec",
  "#b3d6ed",
  "#ffe8ec",
]
