[meta]
name = "luka"
group = "Vocaloid"
order = 6
ansi_source = "Rose Pine"

[colors]
background = "#221724"
foreground = "#e0def4"
cursor = "#ffbacc"
selection_background = "#452f3f"
ansi = [
  "#26233a",
  "#eb6f92",
  "#31748f",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",

  "#6e6a86",
  "#eb6f92",
  "#31748f",
  "#f6c177",
  "#9ccfd8",
  "#c4a7e7",
  "#ebbcba",
  "#e0def4",
]
