[meta]
name = "madoka"
group = "Madoka Magica"
order = 15
ansi_source = "Elegant + Magica"
booru = "kaname_madoka"
signature = ["cursor", "ansi1", "ansi3"]

[colors]
background = "#201516"
foreground = "#fbdbdd"
cursor = "#ffc1c6"
selection_background = "#553444"
ansi = [
  "#2d2021",
  "#ff7386",
  "#c2aa48",
  "#e6b271",
  "#af95d2",
  "#dc9299",
  "#aaaaf3",
  "#d7c1c2",

  "#857374",
  "#ffaab2",
  "#e4cb65",
  "#ffd4be",
  "#d1b5f5",
  "#ffb2b9",
  "#d5cbff",
  "#ffe9e9",
]
