[meta]
name = "magi"
group = "Evangelion"
order = 14
ansi_source = "lotap/magi-theme"
signature = ["cursor", "ansi10", "ansi9"]

[colors]
background = "#20150f"
foreground = "#fcdccd"
cursor = "#ec7420"
selection_background = "#5c3230"
ansi = [
  "#2d211b",
  "#ff7850",
  "#a2b631",
  "#ffa938",
  "#b591dd",
  "#e68c9e",
  "#00c6b3",
  "#d7c2b9",

  "#85746b",
  "#ffaca1",
  "#8ae16a",
  "#ffd6a4",
  "#b9b6ff",
  "#ffb1c0",
  "#39f0ad",
  "#ffeae0",
]
