[meta]
name = "mami"
group = "Madoka Magica"
order = 19
ansi_source = "Selenized Black"
signature = ["cursor", "foreground", "ansi11"]

[colors]
background = "#1b170c"
foreground = "#e3e2e2"
cursor = "#efcf65"
selection_background = "#453e1f"
ansi = [
  "#272318",
  "#f8801d",
  "#a2b506",
  "#deb832",
  "#00b2b7",
  "#ff8166",
  "#75c27e",
  "#cec6b4",

  "#7d7767",
  "#ffaf7a",
  "#c2d735",
  "#ffd96c",
  "#00d6dc",
  "#ffb4a4",
  "#95e49c",
  "#f9edd0",
]
