[meta]
name = "mami"
group = "Madoka Magica"
order = 19
ansi_source = "Selenized Black"
booru = "tomoe_mami"
signature = ["cursor", "foreground", "ansi11"]

[colors]
background = "#1b170c"
foreground = "#e3e2e2"
cursor = "#efcf65"
selection_background = "#453e1f"
ansi = [
  "#272318",
  "#ff784a",
  "#a2b506",
  "#deb832",
  "#00b2b7",
  "#fb7c9f",
  "#75c27e",
  "#cec6b4",

  "#7d7767",
  "#ffad91",
  "#c2d735",
  "#ffd96c",
  "#00d6dc",
  "#fdb1c2",
  "#95e49c",
  "#f9edd0",
]
