[meta]
name = "marisa"
group = "Touhou Project"
order = 92
ansi_source = "Apple Classic"
signature = ["cursor", "foreground", "ansi1"]

[colors]
background = "#1b170c"
foreground = "#f0e2c0"
cursor = "#ffd700"
selection_background = "#473d15"
ansi = [
  "#272418",
  "#c91b00",
  "#95b822",
  "#cebe00",
  "#e977d6",
  "#ff8076",
  "#5fc486",
  "#cdc6b4",

  "#7c7767",
  "#ffaf79",
  "#b0db49",
  "#f0e049",
  "#ffa4e0",
  "#ffb3ae",
  "#7de7a4",
  "#f8edd1",
]
