[meta]
name = "mars"
group = "Sailor Moon"
order = 39
ansi_source = "Red Planet + Senshi"
signature = ["cursor", "ansi9", "foreground"]

[colors]
background = "#201514"
foreground = "#c2b790"
cursor = "#d31e30"
selection_background = "#463757"
ansi = [
  "#2d2120",
  "#f18073",
  "#bcab61",
  "#f4ac6f",
  "#ac97cd",
  "#d194b6",
  "#a7ade3",
  "#d7c1c0",

  "#857372",
  "#d9604d",
  "#decc7e",
  "#ffd6a0",
  "#b1ca8a",
  "#ffb2b9",
  "#d1ccff",
  "#ffe9e7",
]
