[meta]
name = "mars"
group = "Sailor Moon"
order = 39
ansi_source = "Red Planet + Senshi"
booru = "sailor_mars"
signature = ["cursor", "ansi9", "foreground"]

[colors]
background = "#201514"
foreground = "#eee2b9"
cursor = "#ee6463"
selection_background = "#463757"
ansi = [
  "#2d2120",
  "#f18073",
  "#b7ad63",
  "#f4ac6f",
  "#ac97cd",
  "#d194b6",
  "#8eb5e2",
  "#d7c1c0",

  "#857372",
  "#ffac9e",
  "#d8ce80",
  "#ffd6a0",
  "#b8bbed",
  "#fdb2c3",
  "#b3d7ff",
  "#ffe9e7",
]
