[meta]
name = "mayuri"
group = "Steins;Gate"
order = 23
ansi_source = "Iceberg Dark"
booru = "shiina_mayuri"
signature = ["cursor", "foreground", "ansi13"]

[colors]
background = "#11191c"
foreground = "#e0e2eb"
cursor = "#9bd5f0"
selection_background = "#2b3f57"
ansi = [
  "#1d2529",
  "#c48bdc",
  "#7db897",
  "#bcc078",
  "#79a5ca",
  "#93a5d7",
  "#7abacd",
  "#c0c8cd",

  "#70787d",
  "#e1aff6",
  "#9dd9b7",
  "#dde297",
  "#9ac6ec",
  "#cdbef7",
  "#9bdbef",
  "#e1f0f9",
]
