[meta]
name = "mayuri"
group = "Steins;Gate"
native = "シュタインズ・ゲート"
order = 23
ansi_source = "Iceberg Dark"

[colors]
background = "#151a28"
foreground = "#cde3f5"
cursor = "#a8d3e8"
selection_background = "#263a52"
ansi = [
  "#1e2132",
  "#e27878",
  "#b4be82",
  "#e2a478",
  "#84a0c6",
  "#a093c7",
  "#89b8c2",
  "#c6c8d1",

  "#6b7089",
  "#e98989",
  "#c0ca8e",
  "#e9b189",
  "#91acd1",
  "#ada0d3",
  "#95c4ce",
  "#d2d4de",
]
