[meta]
name = "megumi"
group = "Jujutsu Kaisen"
order = 104
ansi_source = "Night Owl + Jujutsu"
booru = "fushiguro_megumi"
signature = ["cursor", "ansi11", "ansi3"]

[colors]
background = "#13181e"
foreground = "#dae3f1"
cursor = "#6794c2"
selection_background = "#224156"
ansi = [
  "#1f242a",
  "#fe6fa5",
  "#4fbf8e",
  "#ddb66d",
  "#88a1d0",
  "#ad97f4",
  "#00c3d3",
  "#c2c7cf",

  "#73777f",
  "#ffabc5",
  "#5fe3aa",
  "#eedd8e",
  "#9dc3ff",
  "#cbbefd",
  "#85dfef",
  "#e6effc",
]
