[meta]
name = "meiko"
group = "Vocaloid"
order = 8
ansi_source = "Sundried + Crypton"
booru = "meiko_(vocaloid)"
signature = ["cursor", "ansi11", "ansi14"]

[meta.booru_sites]
konachan = "meiko"
yande = "meiko"

[colors]
background = "#201514"
foreground = "#fcdbda"
cursor = "#ee6368"
selection_background = "#5a323a"
ansi = [
  "#2d2120",
  "#f27f78",
  "#a1b66d",
  "#fda680",
  "#b591de",
  "#f086a2",
  "#b4b17b",
  "#d7c1c1",

  "#857372",
  "#ffabaa",
  "#e4cf1a",
  "#ffd4c3",
  "#d6b3ff",
  "#fdb2c3",
  "#f2cd7e",
  "#ffe9e8",
]
