[meta]
name = "meiko"
group = "Vocaloid"
order = 8
ansi_source = "Sundried + Crypton"
signature = ["cursor", "ansi11", "ansi14"]

[colors]
background = "#201514"
foreground = "#fcdbda"
cursor = "#c9283a"
selection_background = "#5a323a"
ansi = [
  "#2d2120",
  "#f27f78",
  "#c5a85d",
  "#fda680",
  "#bb8fd9",
  "#f38692",
  "#e3a370",
  "#d7c1c1",

  "#857372",
  "#ffabaa",
  "#f4c800",
  "#fc6a21",
  "#dfaeff",
  "#ffb2b9",
  "#fad484",
  "#ffe9e8",
]
