[meta]
name = "meiko"
group = "Vocaloid"
order = 8
ansi_source = "Sundried + Crypton"
booru = "meiko_(vocaloid)"
signature = ["cursor", "ansi11", "ansi14"]

[meta.booru_sites]
konachan = "meiko"
yande = "meiko"

[colors]
background = "#201514"
foreground = "#fcdbda"
cursor = "#ee6368"
selection_background = "#5a323a"
ansi = [
  "#2d2120",
  "#f27f78",
  "#c5a85d",
  "#fda680",
  "#bb8fd9",
  "#f38692",
  "#78bdb2",
  "#d7c1c1",

  "#857372",
  "#ffabaa",
  "#f4c800",
  "#ffd4c3",
  "#dfaeff",
  "#ffb2b9",
  "#f2cd7e",
  "#ffe9e8",
]
