[meta]
name = "mercury"
group = "Sailor Moon"
order = 38
ansi_source = "Glacier + Senshi"
signature = ["cursor", "ansi12", "ansi2"]

[colors]
background = "#12181d"
foreground = "#d8e4f0"
cursor = "#3c9cd7"
selection_background = "#293f59"
ansi = [
  "#1e242a",
  "#d67df1",
  "#51bf86",
  "#f4ae54",
  "#51a8e1",
  "#e480ee",
  "#8fb4de",
  "#c1c7ce",

  "#72787e",
  "#fca0ff",
  "#00e3dc",
  "#9eefb1",
  "#73cafd",
  "#ffa9fc",
  "#aed6ff",
  "#e4effb",
]
