[meta]
name = "mercury"
group = "Sailor Moon"
order = 38
ansi_source = "Glacier + Senshi"
booru = "sailor_mercury"
signature = ["cursor", "ansi12", "ansi2"]

[colors]
background = "#12181d"
foreground = "#d8e4f0"
cursor = "#3c9cd7"
selection_background = "#293f59"
ansi = [
  "#1e242a",
  "#ff6ea5",
  "#51bf86",
  "#f4ae54",
  "#51a8e1",
  "#e480ee",
  "#93b3df",
  "#c1c7ce",

  "#72787e",
  "#ffabc5",
  "#34e4c6",
  "#f6d67b",
  "#73cafd",
  "#ffa9fc",
  "#b2d5ff",
  "#e4effb",
]
