[meta]
name = "mettaton"
group = "Undertale"
order = 60
ansi_source = "Laser"
booru = "mettaton"
signature = ["cursor", "ansi13", "ansi3"]

[meta.booru_sites]
yande = []

[colors]
background = "#1d151b"
foreground = "#f3dceb"
cursor = "#d468ca"
selection_background = "#52344d"
ansi = [
  "#2a2128",
  "#f37b98",
  "#b3b620",
  "#dbb92a",
  "#829df1",
  "#ea7ee5",
  "#83b7d7",
  "#d1c2cb",

  "#80747b",
  "#f8acbd",
  "#dbd079",
  "#f8d9b1",
  "#acbfff",
  "#fbacf6",
  "#a7d8f7",
  "#fee8f6",
]
