[meta]
name = "mettaton"
group = "Undertale"
order = 60
ansi_source = "Laser"
signature = ["cursor", "ansi12", "ansi4"]

[colors]
background = "#150a14"
foreground = "#f4e3ee"
cursor = "#ef11ec"
selection_background = "#3a1038"
ansi = [
  "#626262",
  "#ff8373",
  "#b4fb73",
  "#09b4bd",
  "#fed300",
  "#ff90fe",
  "#d1d1fe",
  "#f1f1f1",

  "#8f8f8f",
  "#ffc4be",
  "#d6fcba",
  "#fffed5",
  "#f92883",
  "#ffb2fe",
  "#e6e7fe",
  "#ffffff",
]
