[meta]
name = "mettaton"
group = "Undertale"
order = 60
ansi_source = "Laser"
signature = ["cursor", "ansi12", "ansi4"]

[colors]
background = "#1d151b"
foreground = "#f3dceb"
cursor = "#ef11ec"
selection_background = "#52344d"
ansi = [
  "#2a2128",
  "#f37b98",
  "#e99b00",
  "#8cbfff",
  "#fed300",
  "#ea7ee5",
  "#bda7de",
  "#d1c2cb",

  "#80747b",
  "#f8acbd",
  "#f6c478",
  "#ffd5b6",
  "#f92883",
  "#fbacf6",
  "#dbc9ff",
  "#fee8f6",
]
