[meta]
name = "miku"
group = "Vocaloid"
order = 2
ansi_source = "vauxe Miku"
booru = "hatsune_miku"
signature = ["cursor", "ansi1", "ansi12"]

[colors]
background = "#101918"
foreground = "#d3e6e3"
cursor = "#39c5bb"
selection_background = "#234246"
ansi = [
  "#1c2524",
  "#e87eb3",
  "#2fc189",
  "#b2c380",
  "#7ea0da",
  "#a99cd9",
  "#27c5b3",
  "#bec9c6",

  "#6f7977",
  "#ffa9c0",
  "#40e6a5",
  "#d3e49e",
  "#b7bcff",
  "#ccbdf3",
  "#23e9e1",
  "#dff2ef",
]
