[meta]
name = "miku"
group = "Vocaloid"
order = 2
ansi_source = "vauxe Miku"
booru = "hatsune_miku"
signature = ["cursor", "ansi1", "ansi12"]

[colors]
background = "#101918"
foreground = "#d3e6e3"
cursor = "#39c5bb"
selection_background = "#234246"
ansi = [
  "#1c2524",
  "#e87eb3",
  "#00c294",
  "#b2c380",
  "#6aa6d6",
  "#95a3de",
  "#27c5b3",
  "#bec9c6",

  "#6f7977",
  "#ffa9c0",
  "#00e7b5",
  "#d3e49e",
  "#b7bcff",
  "#b6c5f9",
  "#23e9e1",
  "#dff2ef",
]
