[meta]
name = "mio"
group = "K-On!"
order = 84
ansi_source = "Ardoise + HTT"
signature = ["cursor", "ansi4", "foreground"]

[colors]
background = "#14181e"
foreground = "#e8ecf2"
cursor = "#84aadc"
selection_background = "#373e47"
ansi = [
  "#20242a",
  "#e478df",
  "#12c0ac",
  "#ffa1b0",
  "#2465c2",
  "#b195ff",
  "#16c3d0",
  "#c3c6cf",

  "#73777f",
  "#ffa0fa",
  "#19e5c9",
  "#6ef5b5",
  "#90c5ff",
  "#cfbdff",
  "#60e3f3",
  "#e7eefd",
]
