[meta]
name = "mion"
group = "Higurashi"
order = 68
ansi_source = "Patina Moss"
booru = "sonozaki_mion"
signature = ["cursor", "ansi1", "ansi3"]

[colors]
background = "#141911"
foreground = "#dce6d1"
cursor = "#84b96e"
selection_background = "#3c3f35"
ansi = [
  "#20251d",
  "#d88c8c",
  "#78ba8a",
  "#d0bb6a",
  "#68ada0",
  "#d693ad",
  "#7dbda6",
  "#c3c8bb",

  "#73796e",
  "#f0b677",
  "#98dba9",
  "#dee292",
  "#88cec0",
  "#f9b2cd",
  "#9ddfc6",
  "#e7f1dc",
]
