[meta]
name = "misato"
group = "Evangelion"
order = 12
ansi_source = "Purple Rain"
signature = ["cursor", "ansi13", "foreground"]

[colors]
background = "#201514"
foreground = "#e5e2dd"
cursor = "#ee645d"
selection_background = "#453858"
ansi = [
  "#2d211f",
  "#ff7766",
  "#d7a300",
  "#ffa851",
  "#b38bff",
  "#e088cf",
  "#8ab0ff",
  "#d8c2bf",

  "#857371",
  "#ffaba7",
  "#fcc435",
  "#ffd5ae",
  "#ceb5ff",
  "#d8baff",
  "#b5df7a",
  "#ffe9e7",
]
