[meta]
name = "miyuki"
group = "Lucky☆Star"
order = 28
ansi_source = "Oxocarbon"
signature = ["cursor", "ansi4", "ansi2"]

[colors]
background = "#201516"
foreground = "#fbdbde"
cursor = "#f9a6b2"
selection_background = "#503645"
ansi = [
  "#2d2122",
  "#52a5f8",
  "#00b4ff",
  "#ffa0b9",
  "#00c15a",
  "#e285dc",
  "#ff8db4",
  "#d7c1c3",

  "#847374",
  "#94c4ff",
  "#cec5ff",
  "#ffd1db",
  "#e6bd00",
  "#ffaaf7",
  "#ffc1d2",
  "#ffe9ea",
]
