[meta]
name = "miyuki"
group = "Lucky☆Star"
order = 28
ansi_source = "Tinacious Design Dark + Ryouou"
booru = "takara_miyuki"
signature = ["cursor", "selection", "ansi1"]

[colors]
background = "#201517"
foreground = "#fadbe1"
cursor = "#ffc1d0"
selection_background = "#6e00ab"
ansi = [
  "#2c2123",
  "#dd8895",
  "#d0a600",
  "#ffa76d",
  "#8d98ff",
  "#ce88ff",
  "#71b5ff",
  "#d6c2c5",

  "#847376",
  "#ffa8c2",
  "#f7c600",
  "#ffd4bb",
  "#b6bcff",
  "#ffabef",
  "#b5d4ff",
  "#ffe8ec",
]
