[meta]
name = "monika"
group = "Doki Doki Literature Club"
order = 75
ansi_source = "Hipster Green + DDLC"
booru = "monika_(doki_doki_literature_club)"
signature = ["cursor", "foreground", "ansi3"]

[meta.booru_sites]
konachan = "monika_(ddlc)"
yande = "monika_(doki_doki_literature_club!)"

[colors]
background = "#141911"
foreground = "#d4e8cc"
cursor = "#80ad64"
selection_background = "#26442c"
ansi = [
  "#20251c",
  "#f97a4e",
  "#68bf4e",
  "#c2c207",
  "#00b1c1",
  "#fc7b9f",
  "#4cc3a9",
  "#c4c8bb",

  "#74796d",
  "#ffab90",
  "#9cde7b",
  "#cbea4e",
  "#3ad0ff",
  "#feb1c3",
  "#4deabe",
  "#e8f1db",
]
