[meta]
name = "monika"
group = "Doki Doki Literature Club"
order = 75
ansi_source = "Hipster Green + DDLC"
booru = "monika_(doki_doki_literature_club)"
signature = ["cursor", "foreground", "ansi3"]

[meta.booru_sites]
konachan = "monika_(ddlc)"
yande = "monika_(doki_doki_literature_club!)"

[colors]
background = "#141911"
foreground = "#d4e8cc"
cursor = "#80ad64"
selection_background = "#26442c"
ansi = [
  "#20251c",
  "#ed8700",
  "#69bf4d",
  "#c2c207",
  "#00b1c1",
  "#ff825d",
  "#4cc3a9",
  "#c4c8bb",

  "#74796d",
  "#ffb144",
  "#abdb6f",
  "#cbea4e",
  "#3ad0ff",
  "#ffb59f",
  "#4deabe",
  "#e8f1db",
]
