[meta]
name = "moon"
group = "Sailor Moon"
native = "美少女戦士セーラームーン"
order = 37
ansi_source = "Starlight"

[colors]
background = "#191b2e"
foreground = "#f4eef8"
cursor = "#f48fb1"
selection_background = "#363156"
ansi = [
  "#242424",
  "#f62b5a",
  "#47b413",
  "#e3c401",
  "#24acd4",
  "#f2affd",
  "#13c299",
  "#e6e6e6",

  "#616161",
  "#ff4d51",
  "#35d450",
  "#e9e836",
  "#5dc5f8",
  "#feabf2",
  "#24dfc4",
  "#ffffff",
]
