[meta]
name = "moon"
group = "Sailor Moon"
order = 37
ansi_source = "Starlight"
booru = "sailor_moon"
signature = ["cursor", "ansi3", "ansi12"]

[meta.booru_sites]
konachan = ["tsukino_usagi", "sailor_moon_(character)"]
yande = "tsukino_usagi"

[colors]
background = "#1f1518"
foreground = "#f9dbe2"
cursor = "#f48fb1"
selection_background = "#3e3a5a"
ansi = [
  "#2c2124",
  "#ff7292",
  "#dca100",
  "#d8ba00",
  "#8d9af2",
  "#dd8bc9",
  "#00c6b3",
  "#d5c2c6",

  "#837377",
  "#ffaab2",
  "#fec300",
  "#ffd5ad",
  "#66ccff",
  "#ffaedf",
  "#a5d7ff",
  "#ffe8ed",
]
