[meta]
name = "mugi"
group = "K-On!"
order = 85
ansi_source = "Tomorrow Night Eighties"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#1f1518"
foreground = "#f9dbe2"
cursor = "#f4a7c0"
selection_background = "#463c29"
ansi = [
  "#2c2124",
  "#f57a8e",
  "#c7a859",
  "#e5b451",
  "#72a5d8",
  "#d193bd",
  "#87b3ef",
  "#d5c2c6",

  "#837377",
  "#ffaab5",
  "#eac876",
  "#ffd4bd",
  "#c4b8ff",
  "#f4b3df",
  "#b6d4ff",
  "#ffe8ed",
]
