[meta]
name = "nadeko"
group = "Monogatari"
order = 36
ansi_source = "Tinacious Design Dark"
signature = ["cursor", "ansi4", "ansi2"]

[colors]
background = "#1f1518"
foreground = "#f9dbe3"
cursor = "#f2a0bd"
selection_background = "#53334b"
ansi = [
  "#2c2124",
  "#fa72aa",
  "#3fc267",
  "#ffa671",
  "#00aedb",
  "#eb7de3",
  "#71b5ff",
  "#d5c2c6",

  "#837377",
  "#ffa8c5",
  "#f8c600",
  "#ffd4bc",
  "#b4bdff",
  "#ffaaf4",
  "#b5d4ff",
  "#ffe8ee",
]
