[meta]
name = "nagisa"
group = "Madoka Magica"
order = 20
ansi_source = "Cutie Pro"
booru = "momoe_nagisa"
signature = ["cursor", "foreground", "ansi12"]

[colors]
background = "#1f160d"
foreground = "#e7e2da"
cursor = "#f7941d"
selection_background = "#56361e"
ansi = [
  "#2c2219",
  "#fe7956",
  "#c2aa52",
  "#ffa679",
  "#28ace1",
  "#ea8b90",
  "#a0bc36",
  "#d5c3b6",

  "#837469",
  "#fdae97",
  "#f0c67c",
  "#ffd6ab",
  "#86cbe4",
  "#fdb2c7",
  "#c1da99",
  "#ffeada",
]
