[meta]
name = "natsuki"
group = "Doki Doki Literature Club"
order = 73
ansi_source = "Fairyfloss"
booru = "natsuki_(doki_doki_literature_club)"
signature = ["cursor", "ansi9", "ansi3"]

[meta.booru_sites]
konachan = "natsuki_(ddlc)"
yande = "natsuki_(doki_doki_literature_club!)"

[colors]
background = "#1f1518"
foreground = "#f8dbe3"
cursor = "#ffb8d1"
selection_background = "#4d3552"
ansi = [
  "#2c2124",
  "#fd729e",
  "#acb068",
  "#ddb900",
  "#72a8c5",
  "#d293b5",
  "#6db4f9",
  "#d5c2c6",

  "#837377",
  "#ffaba6",
  "#d6ce82",
  "#f8d9af",
  "#92c8e6",
  "#fab2cc",
  "#abd4ff",
  "#ffe8ee",
]
