[meta]
name = "nazuna"
group = "Call of the Night"
order = 62
ansi_source = "Purplepeter"
signature = ["cursor", "ansi1", "ansi13"]

[colors]
background = "#1e151a"
foreground = "#f4dce9"
cursor = "#e9acd4"
selection_background = "#423859"
ansi = [
  "#2a2127",
  "#fd786c",
  "#d1a361",
  "#f2ac80",
  "#7aa1e9",
  "#e089c7",
  "#00bdfe",
  "#d2c2ca",

  "#81737a",
  "#ffa9b7",
  "#fcc182",
  "#ffd4b9",
  "#a2c1ff",
  "#e2b6fc",
  "#a4d9f9",
  "#ffe8f3",
]
