[meta]
name = "nazuna"
group = "Call of the Night"
order = 62
ansi_source = "Purplepeter"
signature = ["cursor", "ansi1", "ansi13"]

[colors]
background = "#150f26"
foreground = "#ece7fa"
cursor = "#d0b8c5"
selection_background = "#3a2a5e"
ansi = [
  "#0a0520",
  "#ff796d",
  "#99b481",
  "#efdfac",
  "#66d9ef",
  "#e78fcd",
  "#ba8cff",
  "#ffba81",

  "#504b63",
  "#f99f92",
  "#b4be8f",
  "#f2e9bf",
  "#79daed",
  "#ba91d4",
  "#a0a0d6",
  "#b9aed3",
]
