[meta]
name = "neutral"
group = "Default"
order = 1
role = "default"
ansi_source = "Nvim Dark"
signature = ["cursor", "ansi4", "ansi5"]

[colors]
background = "#17171f"
foreground = "#e3e0f3"
cursor = "#cdcdff"
selection_background = "#3e3c4c"
ansi = [
  "#23232b",
  "#ca8fb2",
  "#5db9c3",
  "#f7a895",
  "#72a7c9",
  "#c796c8",
  "#65bbe3",
  "#c7c5d0",

  "#777680",
  "#edaed3",
  "#7fdae5",
  "#ffd3c9",
  "#a1c3f2",
  "#dabaf5",
  "#95dbff",
  "#eeecfe",
]
