[meta]
name = "neutral"
group = "Default"
order = 1
role = "default"
ansi_source = "Nvim Dark"
signature = ["cursor", "ansi4", "ansi5"]

[colors]
background = "#17171f"
foreground = "#e0e2ea"
cursor = "#e0def4"
selection_background = "#2a2837"
ansi = [
  "#07080d",
  "#ffc0b9",
  "#b3f6c0",
  "#fce094",
  "#a6dbff",
  "#ffcaff",
  "#8cf8f7",
  "#eef1f8",

  "#4f5258",
  "#ffc0b9",
  "#b3f6c0",
  "#fce094",
  "#a6dbff",
  "#ffcaff",
  "#8cf8f7",
  "#eef1f8",
]
