[meta]
name = "nightcity"
group = "Cyberpunk: Edgerunners"
order = 90
ansi_source = "Vibrant Ink"
signature = ["cursor", "ansi13", "ansi14"]

[colors]
background = "#19180d"
foreground = "#e8e3c7"
cursor = "#fcee0a"
selection_background = "#423f14"
ansi = [
  "#252418",
  "#e38d00",
  "#a5b400",
  "#daba00",
  "#4bb291",
  "#ff7f83",
  "#5dc2a1",
  "#cbc7b5",

  "#7a7768",
  "#ffb06b",
  "#abdc4d",
  "#e8e330",
  "#2fd1ff",
  "#ff00ff",
  "#00ffff",
  "#f4eed2",
]
