[meta]
name = "nijika"
group = "Bocchi the Rock!"
order = 30
ansi_source = "Medallion"
booru = "ijichi_nijika"
signature = ["cursor", "ansi12", "ansi1"]

[colors]
background = "#1d170c"
foreground = "#f3e0c5"
cursor = "#ffb400"
selection_background = "#493c11"
ansi = [
  "#2a2318",
  "#f97e38",
  "#beac28",
  "#e1b71b",
  "#d289bf",
  "#e68d96",
  "#70bfb2",
  "#d2c5b4",

  "#807567",
  "#ffb065",
  "#e1ce26",
  "#ffd968",
  "#b2bdff",
  "#ffb2b7",
  "#8ae2d3",
  "#ffebd0",
]
