[meta]
name = "nobara"
group = "Jujutsu Kaisen"
order = 105
ansi_source = "Spacedust + Jujutsu"
booru = "kugisaki_nobara"
signature = ["cursor", "ansi4", "ansi3"]

[colors]
background = "#20160e"
foreground = "#faddca"
cursor = "#c08355"
selection_background = "#273f58"
ansi = [
  "#2c211a",
  "#ff7849",
  "#9ab46e",
  "#d3ba63",
  "#929ed1",
  "#ff779e",
  "#6cc382",
  "#d6c3b7",

  "#84746a",
  "#ffad91",
  "#c6d38c",
  "#fcd8a9",
  "#c7baf7",
  "#ffafc2",
  "#a4dfba",
  "#ffeadd",
]
