[meta]
name = "oracle"
group = "Persona 5"
order = 54
ansi_source = "Monokai Remastered"
booru = "sakura_futaba"
signature = ["cursor", "ansi2", "ansi4"]

[colors]
background = "#1f160e"
foreground = "#f9dec8"
cursor = "#fd971f"
selection_background = "#384037"
ansi = [
  "#2c2219",
  "#ff775b",
  "#85bb35",
  "#ffa851",
  "#b48bff",
  "#fb7ca0",
  "#6dc287",
  "#d5c3b6",

  "#837469",
  "#ffac9b",
  "#d5d421",
  "#ffd87d",
  "#b8bbff",
  "#fdb1c2",
  "#8ee4a6",
  "#ffeadb",
]
