[meta]
name = "panther"
group = "Persona 5"
order = 51
ansi_source = "Warm Neon + Phantom"
booru = "takamaki_anne"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#201514"
foreground = "#fcdbd8"
cursor = "#ee6460"
selection_background = "#5c3233"
ansi = [
  "#2d2120",
  "#ff7671",
  "#8dbd4c",
  "#bcc326",
  "#7f9bff",
  "#fe78ba",
  "#77b6fd",
  "#d8c2c0",

  "#857371",
  "#ffaba8",
  "#d1d282",
  "#f1dd9f",
  "#c4baff",
  "#ffb1c4",
  "#b3d6fe",
  "#ffe9e7",
]
