[meta]
name = "papyrus"
group = "Undertale"
order = 58
ansi_source = "Ubuntu + Determination"
signature = ["cursor", "foreground", "ansi4"]

[colors]
background = "#22091b"
foreground = "#f1ede4"
cursor = "#f34511"
selection_background = "#4a1638"
ansi = [
  "#2e3436",
  "#cc0000",
  "#4e9a06",
  "#c4a000",
  "#3465a4",
  "#ad7fa8",
  "#06989a",
  "#d3d7cf",

  "#555753",
  "#ef2929",
  "#8ae234",
  "#fce94f",
  "#729fcf",
  "#ad7fa8",
  "#34e2e2",
  "#eeeeec",
]
