[meta]
name = "papyrus"
group = "Undertale"
order = 58
ansi_source = "Ubuntu + Determination"
booru = "papyrus_(undertale)"
signature = ["cursor", "foreground", "ansi4"]

[meta.booru_sites]
yande = "papyrus"

[colors]
background = "#201512"
foreground = "#e6e2d9"
cursor = "#ec6844"
selection_background = "#563347"
ansi = [
  "#2e211d",
  "#ff775d",
  "#bfae13",
  "#fea933",
  "#75a2e5",
  "#d692ab",
  "#82c07b",
  "#d8c2bc",

  "#85736f",
  "#ffac9e",
  "#e3cf19",
  "#ffd6a0",
  "#b5beff",
  "#fab2cc",
  "#94e58b",
  "#ffe9e4",
]
