[meta]
name = "papyrus"
group = "Undertale"
order = 58
ansi_source = "Ubuntu + Determination"
signature = ["cursor", "foreground", "ansi4"]

[colors]
background = "#201512"
foreground = "#e6e2d9"
cursor = "#ec6844"
selection_background = "#563347"
ansi = [
  "#2e211d",
  "#ff775d",
  "#cca800",
  "#fea933",
  "#75a2e5",
  "#d692ab",
  "#8dbe72",
  "#d8c2bc",

  "#85736f",
  "#ffac9e",
  "#f4c700",
  "#ffd6a0",
  "#d3b4f5",
  "#fab2cc",
  "#a6e27d",
  "#ffe9e4",
]
