[meta]
name = "patchouli"
group = "Touhou Project"
order = 95
ansi_source = "SeedFlip Ultraviolet"
booru = "patchouli_knowledge"
signature = ["cursor", "ansi5", "ansi3"]

[colors]
background = "#1b161d"
foreground = "#ecdef0"
cursor = "#c67ffb"
selection_background = "#443858"
ansi = [
  "#27222a",
  "#f972b0",
  "#00bcd3",
  "#d6bb29",
  "#9097ff",
  "#eb7ee4",
  "#4fb9ff",
  "#cdc3ce",

  "#7c757e",
  "#ffa7ce",
  "#3adeff",
  "#ffd4c2",
  "#b5bcff",
  "#f3afff",
  "#a8d7ff",
  "#f8e9fb",
]
