[meta]
name = "queen"
group = "Persona 5"
order = 53
ansi_source = "Argonaut + Phantom"
signature = ["cursor", "foreground", "ansi4"]

[colors]
background = "#201513"
foreground = "#fffaf4"
cursor = "#ff0018"
selection_background = "#313d5b"
ansi = [
  "#2d211f",
  "#ff7767",
  "#d3a500",
  "#ffa859",
  "#008df8",
  "#ef7cdc",
  "#8cafff",
  "#d8c2bf",

  "#857370",
  "#ffaba5",
  "#fec400",
  "#ffd5ae",
  "#d6b2ff",
  "#ffacec",
  "#b7df70",
  "#ffe9e6",
]
