[meta]
name = "queen"
group = "Persona 5"
order = 53
ansi_source = "Argonaut + Phantom"
booru = "niijima_makoto"
signature = ["cursor", "foreground", "ansi4"]

[colors]
background = "#201513"
foreground = "#e6e2dc"
cursor = "#ee6558"
selection_background = "#313d5b"
ansi = [
  "#2d211f",
  "#ff7767",
  "#c0ae14",
  "#ffa859",
  "#54a3ff",
  "#ef7cdc",
  "#5dbdf4",
  "#d8c2bf",

  "#857370",
  "#ffaba5",
  "#e5d01a",
  "#ffd5ae",
  "#b2c1ff",
  "#ffacec",
  "#90d9ff",
  "#ffe9e6",
]
