[meta]
name = "rebecca"
group = "Cyberpunk: Edgerunners"
order = 89
ansi_source = "Emerald Synth"
signature = ["ansi1", "ansi2", "cursor"]

[colors]
background = "#201516"
foreground = "#fbdbde"
cursor = "#bcf1e5"
selection_background = "#17453c"
ansi = [
  "#2d2122",
  "#ff2a6d",
  "#00e67e",
  "#ffa768",
  "#c08be5",
  "#ff79b1",
  "#8eafff",
  "#d6c2c3",

  "#847375",
  "#ffa9b9",
  "#c0d74b",
  "#ffd5b7",
  "#dcb1f4",
  "#ffb0cb",
  "#bfd1ff",
  "#ffe9ea",
]
