[meta]
name = "rei"
group = "Evangelion"
order = 10
ansi_source = "Idle Toes"
booru = "ayanami_rei"
signature = ["cursor", "ansi9", "foreground"]

[colors]
background = "#12181d"
foreground = "#e2e2e2"
cursor = "#7fb3d5"
selection_background = "#2f3e55"
ansi = [
  "#1e2529",
  "#fe6f9f",
  "#46c08d",
  "#b2c271",
  "#30a7ff",
  "#af95fc",
  "#7fbad6",
  "#c1c7ce",

  "#71787e",
  "#ffaba8",
  "#55e4a8",
  "#d4e39d",
  "#7cc9ff",
  "#c9beff",
  "#9ddbf3",
  "#e3effa",
]
