[meta]
name = "rei"
group = "Evangelion"
order = 10
ansi_source = "Idle Toes"
booru = "ayanami_rei"
signature = ["cursor", "ansi9", "foreground"]

[colors]
background = "#12181d"
foreground = "#e2e2e2"
cursor = "#7fb3d5"
selection_background = "#2f3e55"
ansi = [
  "#1e2529",
  "#d67eee",
  "#00c1a8",
  "#9dc880",
  "#30a7ff",
  "#a798ff",
  "#8eb4de",
  "#c1c7ce",

  "#71787e",
  "#ffaba8",
  "#00e5c8",
  "#b1ebb7",
  "#7cc9ff",
  "#c9beff",
  "#a0daf6",
  "#e3effa",
]
