[meta]
name = "reimu"
group = "Touhou Project"
order = 91
ansi_source = "Firewatch"
signature = ["cursor", "foreground", "ansi3"]

[colors]
background = "#201513"
foreground = "#f7f0ee"
cursor = "#e30d12"
selection_background = "#58333b"
ansi = [
  "#2e211f",
  "#ff7575",
  "#bdad2c",
  "#dfb563",
  "#b292e0",
  "#ff8260",
  "#96aff1",
  "#d8c2be",

  "#857370",
  "#ffaba8",
  "#e0ce4c",
  "#ffd5b3",
  "#d3b3ff",
  "#ffb5a1",
  "#c1d1ff",
  "#ffe9e6",
]
