[meta]
name = "rena"
group = "Higurashi"
order = 67
ansi_source = "Japanesque + Watanagashi"
signature = ["cursor", "foreground", "ansi1"]

[colors]
background = "#20150f"
foreground = "#e4e3d9"
cursor = "#ea8942"
selection_background = "#593525"
ansi = [
  "#2d211a",
  "#ff728d",
  "#bcad28",
  "#faab34",
  "#b391e4",
  "#e08cb3",
  "#7cbf8c",
  "#d7c3b8",

  "#84746a",
  "#fcacaa",
  "#ecc865",
  "#ffd6ab",
  "#cab6fd",
  "#ffaed9",
  "#a9deb1",
  "#ffeade",
]
