[meta]
name = "rentaro"
group = "Black Bullet"
order = 121
ansi_source = "Tomorrow Night + Varanium"
booru = "satomi_rentarou"
signature = ["cursor", "selection", "foreground"]

[colors]
background = "#14181e"
foreground = "#dfe3e7"
cursor = "#4e6692"
selection_background = "#3c4568"
ansi = [
  "#21242b",
  "#e780a4",
  "#70ba96",
  "#f2af7b",
  "#929ed1",
  "#ac9ed5",
  "#7abacd",
  "#c4c6d0",

  "#74777f",
  "#ffa9c5",
  "#91dbb6",
  "#fad8bf",
  "#9fc4ef",
  "#cdbef7",
  "#9bdbef",
  "#e9eefe",
]
