[meta]
name = "rika"
group = "Higurashi"
order = 69
ansi_source = "Nocturnal Winter"
signature = ["cursor", "ansi13", "foreground"]

[colors]
background = "#16171f"
foreground = "#e3e1e9"
cursor = "#818bd9"
selection_background = "#3c3b54"
ansi = [
  "#23232b",
  "#e877d7",
  "#00bdcd",
  "#61cfa6",
  "#729eff",
  "#ea7ee4",
  "#00c3d3",
  "#c7c5d0",

  "#777680",
  "#ffa1f5",
  "#00e1f4",
  "#5df6c3",
  "#acbfff",
  "#ffb1c5",
  "#00e7fa",
  "#edecfe",
]
