[meta]
name = "rikka"
group = "Chuunibyou"
native = "中二病でも恋がしたい!"
order = 97
ansi_source = "Challenger Deep + Delusion"

[colors]
background = "#1e1c31"
foreground = "#cbe1e7"
cursor = "#ffd447"
selection_background = "#343061"
ansi = [
  "#141228",
  "#ff5458",
  "#62d196",
  "#ffd447",
  "#65b2ff",
  "#6a6dab",
  "#63f2f1",
  "#a6b3cc",

  "#565575",
  "#ff8080",
  "#95ffa4",
  "#ffe9aa",
  "#91ddff",
  "#8f92cf",
  "#aaffe4",
  "#cbe3e7",
]
