[meta]
name = "rikka"
group = "Chuunibyou"
order = 97
ansi_source = "Challenger Deep + Delusion"
signature = ["cursor", "ansi12", "ansi1"]

[colors]
background = "#1b170c"
foreground = "#eee1c5"
cursor = "#ffd447"
selection_background = "#3d3a5b"
ansi = [
  "#282318",
  "#ff5458",
  "#88b958",
  "#e0b72a",
  "#00b3ad",
  "#d790bc",
  "#67c383",
  "#cfc6b4",

  "#7d7667",
  "#ffae80",
  "#b0da5c",
  "#f6db8c",
  "#91ddff",
  "#f8b1dd",
  "#aedf9e",
  "#faedd0",
]
