[meta]
name = "rin"
group = "Vocaloid"
order = 4
ansi_source = "Citruszest"
signature = ["cursor", "ansi4", "ansi1"]

[colors]
background = "#1b170c"
foreground = "#efe1c5"
cursor = "#fecb10"
selection_background = "#4a3c16"
ansi = [
  "#282318",
  "#ff7671",
  "#82bb37",
  "#e0b700",
  "#00ace6",
  "#ff7f7f",
  "#70c281",
  "#cfc5b4",

  "#7e7667",
  "#ffad8d",
  "#9fde59",
  "#f5df22",
  "#42d8ad",
  "#ffb3b2",
  "#79e98e",
  "#faedd0",
]
