[meta]
name = "rin"
group = "Vocaloid"
order = 4
ansi_source = "Citruszest"
signature = ["cursor", "ansi4", "ansi1"]

[colors]
background = "#1c1708"
foreground = "#f5eed8"
cursor = "#ffcc11"
selection_background = "#443711"
ansi = [
  "#404040",
  "#ff5454",
  "#00cc7a",
  "#ffd400",
  "#00bfff",
  "#ff90fe",
  "#48d1cc",
  "#bfbfbf",

  "#808080",
  "#ff1a75",
  "#1affa3",
  "#ffff00",
  "#33cfff",
  "#ffb2fe",
  "#00fff2",
  "#f9f9f9",
]
