[meta]
name = "ritsu"
group = "K-On!"
order = 83
ansi_source = "Acid Lime"
signature = ["cursor", "ansi1", "ansi6"]

[colors]
background = "#15120a"
foreground = "#f0ecd4"
cursor = "#f5e93c"
selection_background = "#383310"
ansi = [
  "#131d0c",
  "#ff3344",
  "#97e63c",
  "#eeff5c",
  "#4deca0",
  "#a6ff6b",
  "#50ffb4",
  "#bfe0a4",

  "#4a6b36",
  "#ff3344",
  "#97e63c",
  "#dbff45",
  "#4deca0",
  "#a6ff6b",
  "#50ffb4",
  "#d4efbc",
]
