[meta]
name = "rokkenjima"
group = "Umineko"
order = 81
ansi_source = "Sequoia Retro Dark + Truth"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#1d170c"
foreground = "#f2e0c5"
cursor = "#e8b246"
selection_background = "#3f3c4a"
ansi = [
  "#292318",
  "#d49266",
  "#a2b270",
  "#ffa48e",
  "#75a6c8",
  "#e888b0",
  "#78bdb2",
  "#d1c5b4",

  "#807667",
  "#efb84c",
  "#c3d38e",
  "#ffd4bb",
  "#8acebc",
  "#d3bcf4",
  "#99dfd3",
  "#feebd0",
]
