[meta]
name = "rokkenjima"
group = "Umineko"
order = 81
ansi_source = "Sequoia Retro Dark + Truth"
signature = ["cursor", "ansi3", "ansi4"]

[colors]
background = "#1d170c"
foreground = "#f2e0c5"
cursor = "#e8b246"
selection_background = "#3f3c4a"
ansi = [
  "#292318",
  "#73ad8c",
  "#a2b270",
  "#da674b",
  "#5c87a4",
  "#d19d33",
  "#d9a866",
  "#d1c5b4",

  "#807667",
  "#efb84c",
  "#c3d38e",
  "#ffd4bb",
  "#8acebc",
  "#99d3b0",
  "#fdc984",
  "#feebd0",
]
