[meta]
name = "ryo"
group = "Bocchi the Rock!"
order = 31
ansi_source = "TokyoNight Storm"
booru = "yamada_ryou"
signature = ["cursor", "ansi4", "ansi6"]

[colors]
background = "#19180d"
foreground = "#e7e3c8"
cursor = "#d6d233"
selection_background = "#333d5b"
ansi = [
  "#252419",
  "#f87b52",
  "#9bb649",
  "#d8b86a",
  "#779ff4",
  "#f184a3",
  "#67bae9",
  "#cac7b6",

  "#797769",
  "#ffac91",
  "#bbd766",
  "#fbd987",
  "#7cc4ff",
  "#ffb1c4",
  "#73dff9",
  "#f2efd3",
]
