[meta]
name = "ryo"
group = "Bocchi the Rock!"
order = 31
ansi_source = "TokyoNight Storm"
signature = ["cursor", "ansi4", "ansi6"]

[colors]
background = "#1e2233"
foreground = "#c0caf5"
cursor = "#d6d233"
selection_background = "#364a82"
ansi = [
  "#1d202f",
  "#f7768e",
  "#9ece6a",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#a9b1d6",

  "#4e5575",
  "#f7768e",
  "#9ece6a",
  "#e0af68",
  "#7aa2f7",
  "#bb9af7",
  "#7dcfff",
  "#c0caf5",
]
