[meta]
name = "sans"
group = "Undertale"
order = 57
ansi_source = "Galaxy"
signature = ["cursor", "foreground", "ansi11"]

[colors]
background = "#12181d"
foreground = "#eef3fb"
cursor = "#3ec1ff"
selection_background = "#2f3e59"
ansi = [
  "#1e2529",
  "#d47ef3",
  "#00bebf",
  "#32d585",
  "#45a6f6",
  "#a899f8",
  "#45baff",
  "#c1c7ce",

  "#71787e",
  "#e8abfd",
  "#4fe0e4",
  "#ffff55",
  "#8dc6ff",
  "#dab9ff",
  "#add6ff",
  "#e3f0fa",
]
