[meta]
name = "sans"
group = "Undertale"
order = 57
ansi_source = "Galaxy"
booru = "sans_(undertale)"
signature = ["cursor", "foreground", "ansi11"]

[meta.booru_sites]
konachan = "sans"
yande = "sans"

[colors]
background = "#12181d"
foreground = "#dee3eb"
cursor = "#3ec1ff"
selection_background = "#2f3e59"
ansi = [
  "#1e2529",
  "#ff6ea5",
  "#51be8e",
  "#91ca43",
  "#45a6f6",
  "#a899f8",
  "#25bef7",
  "#c1c7ce",

  "#71787e",
  "#ffa9c4",
  "#78e1b0",
  "#e4e43b",
  "#8dc6ff",
  "#dab9ff",
  "#a2daf9",
  "#e3f0fa",
]
