[meta]
name = "satoko"
group = "Higurashi"
order = 70
ansi_source = "Espresso"
signature = ["cursor", "ansi9", "ansi12"]

[colors]
background = "#1b170c"
foreground = "#ede2c5"
cursor = "#e4c767"
selection_background = "#4c3a28"
ansi = [
  "#272318",
  "#f78027",
  "#adb146",
  "#e2b55a",
  "#68ad9f",
  "#eb8b8d",
  "#76bcbe",
  "#cec6b4",

  "#7d7767",
  "#f00c0c",
  "#cfd25d",
  "#e9df84",
  "#8ab7d9",
  "#ffb3b4",
  "#9ddfc6",
  "#f9edd0",
]
