[meta]
name = "satoko"
group = "Higurashi"
order = 70
ansi_source = "Espresso"
booru = "houjou_satoko"
signature = ["cursor", "ansi9", "ansi12"]

[colors]
background = "#1b170c"
foreground = "#ede2c5"
cursor = "#e4c767"
selection_background = "#4c3a28"
ansi = [
  "#272318",
  "#f78027",
  "#adb146",
  "#e2b55a",
  "#68a9be",
  "#e88aa2",
  "#76bcbe",
  "#cec6b4",

  "#7d7767",
  "#ffac9f",
  "#cfd25d",
  "#f4db81",
  "#97c7eb",
  "#fdb2c3",
  "#98dfce",
  "#f9edd0",
]
