[meta]
name = "sayaka"
group = "Madoka Magica"
order = 17
ansi_source = "Teerb + Magica"
signature = ["cursor", "ansi4", "foreground"]

[colors]
background = "#11191c"
foreground = "#d0d0d0"
cursor = "#88afc0"
selection_background = "#293f59"
ansi = [
  "#1d2528",
  "#ba92ca",
  "#61bc9a",
  "#afc382",
  "#5b7397",
  "#a2a1d7",
  "#60c0b8",
  "#c0c8cc",

  "#70787c",
  "#dcb2ec",
  "#82deba",
  "#cfe5a2",
  "#8ec9e2",
  "#c3c1f9",
  "#97dee1",
  "#e1f0f8",
]
