[meta]
name = "sayaka"
group = "Madoka Magica"
order = 17
ansi_source = "Teerb + Magica"
booru = "miki_sayaka"
signature = ["cursor", "ansi4", "foreground"]

[colors]
background = "#11191c"
foreground = "#e3e2e2"
cursor = "#76b1ca"
selection_background = "#293f59"
ansi = [
  "#1d2528",
  "#d38ba2",
  "#67bc94",
  "#afc382",
  "#85a2cf",
  "#aa9ed4",
  "#60c0b8",
  "#c0c8cc",

  "#70787c",
  "#f6abc3",
  "#82deba",
  "#d5e39e",
  "#95c6e8",
  "#cabff6",
  "#97dee1",
  "#e1f0f8",
]
