[meta]
name = "sei"
group = "VA-11 Hall-A"
order = 47
ansi_source = "Blue Matrix"
signature = ["cursor", "ansi12", "ansi9"]

[colors]
background = "#101916"
foreground = "#d4e7df"
cursor = "#7bcdb5"
selection_background = "#293f59"
ansi = [
  "#1c2622",
  "#e28d00",
  "#00c38a",
  "#88ce5a",
  "#00b0cc",
  "#6da7ff",
  "#44bfdc",
  "#bfc9c4",

  "#6f7975",
  "#ffaba5",
  "#4de693",
  "#adef80",
  "#b8bcff",
  "#acc7ff",
  "#47e8db",
  "#e0f2ea",
]
