[meta]
name = "sei"
group = "VA-11 Hall-A"
native = "Cyberpunk Bartender Action"
order = 47
ansi_source = "Blue Matrix"

[colors]
background = "#0e1420"
foreground = "#e8f4ff"
cursor = "#7bcdb5"
selection_background = "#14304d"
ansi = [
  "#101116",
  "#ff5680",
  "#00ff9c",
  "#fffc58",
  "#00b0ff",
  "#d57bff",
  "#76c1ff",
  "#c7c7c7",

  "#686868",
  "#ff6e67",
  "#5ffa68",
  "#fffc67",
  "#6871ff",
  "#d682ec",
  "#60fdff",
  "#ffffff",
]
