[meta]
name = "shinka"
group = "Chuunibyou"
order = 99
ansi_source = "Everforest Dark Hard + Delusion"
signature = ["cursor", "ansi11", "ansi12"]

[colors]
background = "#1f1519"
foreground = "#f7dbe6"
cursor = "#d898b7"
selection_background = "#4d3743"
ansi = [
  "#2b2125",
  "#ff7291",
  "#d3a35f",
  "#f4ab84",
  "#7ca4cc",
  "#d393b2",
  "#6cbfb2",
  "#d4c2c8",

  "#827379",
  "#ffaab6",
  "#ffc07a",
  "#ffd794",
  "#77cafe",
  "#ffaedb",
  "#63e6d4",
  "#ffe8f0",
]
