[meta]
name = "shinobu"
group = "Monogatari"
order = 34
ansi_source = "Mona Lisa + Oddity"
signature = ["cursor", "ansi9", "ansi13"]

[colors]
background = "#1c170c"
foreground = "#efe1c5"
cursor = "#f2c230"
selection_background = "#4f3a1d"
ansi = [
  "#282318",
  "#f78019",
  "#b9ac62",
  "#faab46",
  "#77ac87",
  "#ff843b",
  "#a7b876",
  "#cfc5b4",

  "#7e7667",
  "#ff4331",
  "#dccd7a",
  "#ffd5b3",
  "#96cea7",
  "#ff5b6a",
  "#c1dc81",
  "#fbecd0",
]
