[meta]
name = "shinobu"
group = "Monogatari"
order = 34
ansi_source = "Mona Lisa + Oddity"
booru = "oshino_shinobu"
signature = ["cursor", "ansi9", "ansi13"]

[colors]
background = "#1c170c"
foreground = "#efe1c5"
cursor = "#f2c230"
selection_background = "#4f3a1d"
ansi = [
  "#282318",
  "#f78019",
  "#b9ac62",
  "#faab46",
  "#72a7c4",
  "#ff825a",
  "#8ebe89",
  "#cfc5b4",

  "#7e7667",
  "#ffac9f",
  "#dccd7a",
  "#ffd5b3",
  "#92c8e7",
  "#ffb3b4",
  "#a1e39a",
  "#fbecd0",
]
