[meta]
name = "shiro"
group = "No Game No Life"
order = 140
ansi_source = "Duskfox + Blank"
booru = "shiro_(no_game_no_life)"
signature = ["cursor", "ansi1", "selection"]

[colors]
background = "#11191c"
foreground = "#d5e5ec"
cursor = "#9ddbf2"
selection_background = "#6b238d"
ansi = [
  "#1d2528",
  "#ff738a",
  "#7cb89a",
  "#b3c17c",
  "#61aac5",
  "#aa9cda",
  "#77bbc5",
  "#bfc8cc",

  "#70787c",
  "#fca6cb",
  "#9dd9ba",
  "#d5e3a0",
  "#7fcbe8",
  "#e9b3ff",
  "#99dde8",
  "#e1f0f8",
]
