[meta]
name = "sinon"
group = "Sword Art Online"
order = 129
ansi_source = "Catppuccin Macchiato + Aincrad"
booru = "sinon"
signature = ["cursor", "ansi3", "ansi4"]

[meta.booru_sites]
konachan = "shinon_(sao)"

[colors]
background = "#111916"
foreground = "#d5e7dd"
cursor = "#9edfc4"
selection_background = "#4a3a37"
ansi = [
  "#1d2622",
  "#e88462",
  "#77ba85",
  "#b9c266",
  "#74a6cb",
  "#a99ed3",
  "#76bead",
  "#bfc9c3",

  "#707974",
  "#fdac91",
  "#a4d8ad",
  "#d6e49c",
  "#8ec9e4",
  "#cabdfb",
  "#9adfcf",
  "#e0f2e8",
]
