[meta]
name = "skull"
group = "Persona 5"
order = 50
ansi_source = "Desert"
signature = ["cursor", "ansi1", "foreground"]

[colors]
background = "#1b170c"
foreground = "#f5e9c9"
cursor = "#ffd700"
selection_background = "#4c3b15"
ansi = [
  "#272418",
  "#ff2b2b",
  "#91b83a",
  "#cbbd66",
  "#cf963d",
  "#c3a25a",
  "#f09d6a",
  "#cdc6b4",

  "#7c7767",
  "#ffaf7a",
  "#b2da46",
  "#f0e02f",
  "#6cd2c0",
  "#ffb3ad",
  "#f5cf00",
  "#f8edd1",
]
