[meta]
name = "skull"
group = "Persona 5"
order = 50
ansi_source = "Desert"
booru = "sakamoto_ryuuji"
signature = ["cursor", "ansi1", "foreground"]

[colors]
background = "#1b170c"
foreground = "#eee2c2"
cursor = "#f5cf00"
selection_background = "#4c3b15"
ansi = [
  "#272418",
  "#ff766a",
  "#91b83a",
  "#cbbd66",
  "#969be4",
  "#d693ad",
  "#62c0b2",
  "#cdc6b4",

  "#7c7767",
  "#ffae86",
  "#b2da46",
  "#f0e02f",
  "#98befd",
  "#fcb1c3",
  "#00ebd5",
  "#f8edd1",
]
