[meta]
name = "stella"
group = "VA-11 Hall-A"
order = 46
ansi_source = "Scarlet Protocol + Glitch City"
signature = ["cursor", "ansi2", "ansi13"]

[colors]
background = "#201515"
foreground = "#fcdbdb"
cursor = "#ff2e51"
selection_background = "#573245"
ansi = [
  "#2d2121",
  "#ff747d",
  "#00dc84",
  "#ffa768",
  "#ad91ee",
  "#fc78be",
  "#7ab3ff",
  "#d7c1c1",

  "#857373",
  "#ffaba8",
  "#f4c800",
  "#ffd5b4",
  "#e9aaff",
  "#bd35ec",
  "#b7d3ff",
  "#ffe9e8",
]
