[meta]
name = "steph"
group = "No Game No Life"
order = 141
ansi_source = "Catppuccin Mocha + Blank"
booru = "stephanie_dora"
signature = ["cursor", "ansi4", "ansi12"]

[meta.booru_sites]
konachan = []

[colors]
background = "#201516"
foreground = "#fbdbde"
cursor = "#e9607c"
selection_background = "#483b38"
ansi = [
  "#2d2122",
  "#e9819a",
  "#bbae4b",
  "#efae7a",
  "#7e9cff",
  "#d393b2",
  "#8bbe85",
  "#d7c1c3",

  "#847374",
  "#f8acbd",
  "#d9cf7f",
  "#ffd5b7",
  "#95c7e9",
  "#fdafd7",
  "#aee0a8",
  "#ffe9ea",
]
