[meta]
name = "sukuna"
group = "Jujutsu Kaisen"
order = 108
ansi_source = "Hurtado + Jujutsu"
signature = ["cursor", "foreground", "ansi9"]

[colors]
background = "#211513"
foreground = "#dee1e4"
cursor = "#d95845"
selection_background = "#293f59"
ansi = [
  "#2e211e",
  "#f08074",
  "#d3a500",
  "#feaa1b",
  "#a09bd1",
  "#ff78b2",
  "#9aaef5",
  "#d8c2be",

  "#857370",
  "#e33707",
  "#fbc500",
  "#ffd6a3",
  "#d6b2ff",
  "#ffb0ce",
  "#c4d0ff",
  "#ffe9e5",
]
