[meta]
name = "suzaku"
group = "Code Geass"
order = 116
ansi_source = "Eclipse + Geass"
booru = "kururugi_suzaku"
signature = ["cursor", "ansi2", "selection"]

[colors]
background = "#211512"
foreground = "#fddbd3"
cursor = "#945545"
selection_background = "#252968"
ansi = [
  "#2e211e",
  "#ff766a",
  "#90b581",
  "#f9ab52",
  "#979be1",
  "#e189c7",
  "#59c881",
  "#d8c2bd",

  "#85736f",
  "#ffaba3",
  "#c5d949",
  "#ffd5ac",
  "#cdb5ff",
  "#f6b2df",
  "#99e691",
  "#ffe9e4",
]
