[meta]
name = "suzuha"
group = "Steins;Gate"
order = 24
ansi_source = "Gruvbox Dark + Lab"
signature = ["cursor", "ansi9", "ansi4"]

[colors]
background = "#1f160d"
foreground = "#f8dec7"
cursor = "#d98e32"
selection_background = "#423e2b"
ansi = [
  "#2b2218",
  "#fd7b3a",
  "#cca722",
  "#f6ad3c",
  "#458588",
  "#ec8b84",
  "#afb665",
  "#d5c4b5",

  "#837568",
  "#fb4934",
  "#f2c824",
  "#ffd79d",
  "#b0ca8b",
  "#ffb4a7",
  "#d7d776",
  "#ffead9",
]
