[meta]
name = "toriel"
group = "Undertale"
order = 56
ansi_source = "Shades Of Purple + Determination"
signature = ["cursor", "ansi4", "foreground"]

[colors]
background = "#1a180d"
foreground = "#f5f0f5"
cursor = "#ffe700"
selection_background = "#3e3a5a"
ansi = [
  "#262418",
  "#f68112",
  "#91b927",
  "#d1bd00",
  "#7a58ff",
  "#ff843a",
  "#59c48a",
  "#ccc6b5",

  "#7b7768",
  "#ffaf6e",
  "#b0db49",
  "#fadd20",
  "#0dd2ff",
  "#ffb4ab",
  "#83e4bb",
  "#f5eed2",
]
