[meta]
name = "tsubasa"
group = "Monogatari"
order = 35
ansi_source = "Kanso Ink"
booru = "hanekawa_tsubasa"
signature = ["cursor", "foreground", "ansi12"]

[colors]
background = "#201517"
foreground = "#dfe3e1"
cursor = "#fbafc0"
selection_background = "#3a3e45"
ansi = [
  "#2d2123",
  "#dd898e",
  "#b8ae61",
  "#f0ad7c",
  "#7aa7d0",
  "#cc95bd",
  "#80bad6",
  "#d6c2c5",

  "#847376",
  "#ffaab5",
  "#dacf7f",
  "#fdd5b8",
  "#8ec9e2",
  "#e5b8ea",
  "#aad7fe",
  "#ffe8ec",
]
