[meta]
name = "tsubasa"
group = "Monogatari"
order = 35
ansi_source = "Kanso Ink"
signature = ["cursor", "foreground", "ansi12"]

[colors]
background = "#201517"
foreground = "#dfe3e1"
cursor = "#fbafc0"
selection_background = "#3a3e45"
ansi = [
  "#2d2123",
  "#dd898e",
  "#cba65f",
  "#f0ad7c",
  "#989dd2",
  "#cc95bd",
  "#90b4de",
  "#d6c2c5",

  "#847376",
  "#ffaab5",
  "#e6ca7c",
  "#ffd4bb",
  "#8ec9e2",
  "#e5b8ea",
  "#aad7fe",
  "#ffe8ec",
]
