[meta]
name = "tsukasa"
group = "Lucky☆Star"
order = 27
ansi_source = "Sublette + Ryouou"
booru = "hiiragi_tsukasa"
signature = ["cursor", "ansi11", "selection"]

[colors]
background = "#1b161d"
foreground = "#eddeef"
cursor = "#c8a6da"
selection_background = "#2f4090"
ansi = [
  "#27222a",
  "#f374c0",
  "#00bdd0",
  "#faa78d",
  "#8b9bf1",
  "#b999d4",
  "#53b9ff",
  "#cdc3ce",

  "#7c747e",
  "#ffa8c5",
  "#00e2e8",
  "#eede89",
  "#b1bdff",
  "#d7baff",
  "#85ddff",
  "#f8e9fb",
]
