[meta]
name = "tsukasa"
group = "Lucky☆Star"
order = 27
ansi_source = "Sublette"
signature = ["cursor", "ansi13", "ansi12"]

[colors]
background = "#19180d"
foreground = "#e7e3c8"
cursor = "#efe95a"
selection_background = "#433859"
ansi = [
  "#252419",
  "#f97e25",
  "#7ebc3c",
  "#d0bb69",
  "#00b1c4",
  "#ff825a",
  "#4ec68b",
  "#cac7b5",

  "#7a7768",
  "#ffb06a",
  "#addb4f",
  "#e5e25d",
  "#77bbff",
  "#aa88ff",
  "#8be778",
  "#f3efd3",
]
