[meta]
name = "undyne"
group = "Undertale"
order = 59
ansi_source = "Sea Shells + Determination"
booru = "undyne"
signature = ["cursor", "ansi2", "ansi3"]

[meta.booru_sites]
konachan = []

[colors]
background = "#201513"
foreground = "#fddbd6"
cursor = "#ee6557"
selection_background = "#244056"
ansi = [
  "#2e211f",
  "#ff7857",
  "#5cb6d7",
  "#ffa945",
  "#9f98e1",
  "#b795e2",
  "#88b6e9",
  "#d8c2be",

  "#857370",
  "#ffac9f",
  "#8cd8e0",
  "#ffd4b9",
  "#b3bdff",
  "#cabef5",
  "#b3d6fe",
  "#ffe9e6",
]
