[meta]
name = "undyne"
group = "Undertale"
order = 59
ansi_source = "Sea Shells + Determination"
signature = ["cursor", "ansi2", "ansi3"]

[colors]
background = "#201513"
foreground = "#fddbd6"
cursor = "#ee6557"
selection_background = "#244056"
ansi = [
  "#2e211f",
  "#ff7857",
  "#5cb6d7",
  "#ffa945",
  "#9f98e1",
  "#94a1ef",
  "#9faeeb",
  "#d8c2be",

  "#857370",
  "#ffac9f",
  "#9dd9b9",
  "#ffd4b9",
  "#b3bdff",
  "#b9c4fa",
  "#c3d0ff",
  "#ffe9e6",
]
