[meta]
name = "valhalla"
group = "VA-11 Hall-A"
order = 48
ansi_source = "Synthwave + Glitch City"
signature = ["cursor", "ansi6", "ansi3"]

[colors]
background = "#1f1518"
foreground = "#f9dbe3"
cursor = "#f6188f"
selection_background = "#563347"
ansi = [
  "#2c2124",
  "#fb72a9",
  "#d9a200",
  "#fdf834",
  "#ac8eff",
  "#ff7f7c",
  "#12c3e2",
  "#d5c2c6",

  "#837377",
  "#ffa7c8",
  "#ffc313",
  "#ffd5b0",
  "#c3b8ff",
  "#ffb3ad",
  "#c2d1ff",
  "#ffe8ed",
]
