[meta]
name = "valhalla"
group = "VA-11 Hall-A"
order = 48
ansi_source = "Synthwave + Glitch City"
signature = ["cursor", "ansi6", "ansi3"]

[colors]
background = "#1f1518"
foreground = "#f9dbe3"
cursor = "#e76299"
selection_background = "#563347"
ansi = [
  "#2c2124",
  "#fb72a9",
  "#96bc45",
  "#c5c100",
  "#ac8eff",
  "#ec81c9",
  "#09c1e0",
  "#d5c2c6",

  "#837377",
  "#ffa7c8",
  "#ded228",
  "#f1dcab",
  "#c3b8ff",
  "#f1b3dd",
  "#a9daf8",
  "#ffe8ed",
]
