[meta]
name = "velvet"
group = "Persona 5"
native = "ペルソナ5"
order = 55
ansi_source = "Tomorrow Night Blue"

[colors]
background = "#131535"
foreground = "#ffffff"
cursor = "#ffd700"
selection_background = "#2833ab"
ansi = [
  "#000000",
  "#ff9da4",
  "#d1f1a9",
  "#ffeead",
  "#bbdaff",
  "#ebbbff",
  "#99ffff",
  "#ffffff",

  "#4c4c4c",
  "#ff9da4",
  "#d1f1a9",
  "#ffeead",
  "#bbdaff",
  "#ebbbff",
  "#99ffff",
  "#ffffff",
]
