[meta]
name = "venus"
group = "Sailor Moon"
order = 41
ansi_source = "Earthsong"
booru = "sailor_venus"
signature = ["cursor", "ansi3", "ansi12"]

[colors]
background = "#1e160d"
foreground = "#f5dfc6"
cursor = "#f7a700"
selection_background = "#4d3a1e"
ansi = [
  "#2a2218",
  "#ff784a",
  "#b1b100",
  "#f5ae2e",
  "#49aad8",
  "#f97b9e",
  "#3cc4b3",
  "#d3c4b4",

  "#817567",
  "#ffad92",
  "#d7d119",
  "#feda63",
  "#52d0f4",
  "#ffafc2",
  "#00ead4",
  "#ffebd4",
]
