[meta]
name = "venus"
group = "Sailor Moon"
order = 41
ansi_source = "Earthsong"
signature = ["cursor", "ansi3", "ansi12"]

[colors]
background = "#251c12"
foreground = "#e5c7a9"
cursor = "#f7a700"
selection_background = "#4d3a1e"
ansi = [
  "#121418",
  "#c94234",
  "#85c54c",
  "#f5ae2e",
  "#1398b9",
  "#d0633d",
  "#509552",
  "#e5c6aa",

  "#675f54",
  "#ff645a",
  "#98e036",
  "#e0d561",
  "#5fdaff",
  "#ff9269",
  "#84f088",
  "#f6f7ec",
]
