[meta]
name = "yofukashi"
group = "Call of the Night"
order = 66
ansi_source = "Bright Lights"
signature = ["cursor", "ansi5", "ansi4"]

[colors]
background = "#1d170c"
foreground = "#f3e0c5"
cursor = "#ffc251"
selection_background = "#393b5b"
ansi = [
  "#2a2318",
  "#fe7a3e",
  "#b1b029",
  "#ecb142",
  "#76d4ff",
  "#ba76e7",
  "#8dbd84",
  "#d2c5b4",

  "#807667",
  "#ffad8c",
  "#d3d249",
  "#ffd796",
  "#6ed4ad",
  "#ffb1c1",
  "#addfa3",
  "#ffebd0",
]
