[meta]
name = "yofukashi"
group = "Call of the Night"
order = 66
ansi_source = "Bright Lights"
signature = ["cursor", "ansi5", "ansi4"]

[colors]
background = "#191c46"
foreground = "#e8ecfa"
cursor = "#ffc251"
selection_background = "#2c2f6b"
ansi = [
  "#191919",
  "#ff355b",
  "#b7e876",
  "#ffc251",
  "#76d4ff",
  "#ba76e7",
  "#6cbfb5",
  "#c2c8d7",

  "#4c4c4c",
  "#ff355b",
  "#b7e876",
  "#ffc251",
  "#76d5ff",
  "#ba76e7",
  "#6cbfb5",
  "#c2c8d7",
]
