[meta]
name = "youmu"
group = "Touhou Project"
order = 94
ansi_source = "Everforest Dark Med"
booru = "konpaku_youmu"
signature = ["cursor", "foreground", "ansi6"]

[colors]
background = "#101917"
foreground = "#e6e3d3"
cursor = "#0cbba4"
selection_background = "#32413c"
ansi = [
  "#1c2623",
  "#d0962e",
  "#86b78a",
  "#b2c380",
  "#67ada2",
  "#a5a0d6",
  "#81be90",
  "#bec9c5",

  "#6f7976",
  "#f9b500",
  "#84e17a",
  "#cee866",
  "#5fd0e9",
  "#c0c1ff",
  "#71e6c0",
  "#dff2ec",
]
