[meta]
name = "yui"
group = "K-On!"
order = 82
ansi_source = "Espresso Libre + HTT"
booru = "hirasawa_yui"
signature = ["cursor", "ansi11", "ansi13"]

[colors]
background = "#211513"
foreground = "#fddbd5"
cursor = "#ed6650"
selection_background = "#4b3a2b"
ansi = [
  "#2e211e",
  "#ff7761",
  "#c8a900",
  "#fcab00",
  "#cf7ff8",
  "#f18884",
  "#8dbe72",
  "#d8c2be",

  "#857370",
  "#ffaca0",
  "#eeca00",
  "#e6e346",
  "#ceb4ff",
  "#ffb3b5",
  "#a6e27d",
  "#ffe9e5",
]
