[meta]
name = "yuji"
group = "Jujutsu Kaisen"
order = 103
ansi_source = "Rose Pine Moon + Jujutsu"
signature = ["cursor", "ansi3", "ansi1"]

[colors]
background = "#211513"
foreground = "#fddbd6"
cursor = "#d9a097"
selection_background = "#3e3b53"
ansi = [
  "#2e211f",
  "#b53e3f",
  "#a9a4e9",
  "#8f5e3c",
  "#8ea0d1",
  "#d292c0",
  "#ec9c95",
  "#d8c2be",

  "#857370",
  "#ffaab1",
  "#cbc6ff",
  "#ffd5b8",
  "#aec0f3",
  "#f5b2e2",
  "#ffc3be",
  "#ffe9e6",
]
