[meta]
name = "yuri"
group = "Doki Doki Literature Club"
order = 74
ansi_source = "Purple Portal + DDLC"
signature = ["cursor", "ansi11", "ansi9"]

[colors]
background = "#1b161d"
foreground = "#eddeef"
cursor = "#c29ed0"
selection_background = "#4e3551"
ansi = [
  "#282229",
  "#f375b9",
  "#00bae7",
  "#ff99e9",
  "#fb7c47",
  "#7ca4ff",
  "#c89dff",
  "#cec3ce",

  "#7d747e",
  "#fc8d9d",
  "#7cd7ff",
  "#f68bc3",
  "#ffad8c",
  "#adc6ff",
  "#e1c7ff",
  "#f9e9fa",
]
