[meta]
name = "yuri"
group = "Doki Doki Literature Club"
order = 74
ansi_source = "Purple Portal + DDLC"
booru = "yuri_(doki_doki_literature_club)"
signature = ["cursor", "ansi11", "ansi9"]

[colors]
background = "#1b161d"
foreground = "#eddeef"
cursor = "#c29ed1"
selection_background = "#4e3551"
ansi = [
  "#282229",
  "#f375b9",
  "#00bae7",
  "#ffa92e",
  "#9097ff",
  "#7ca4ff",
  "#42bcf5",
  "#cec3ce",

  "#7d747e",
  "#ffaab4",
  "#7cd7ff",
  "#ffd0e4",
  "#b9bcf8",
  "#adc6ff",
  "#a4d8f9",
  "#f9e9fa",
]
