[meta]
name = "yuuki"
group = "Sword Art Online"
order = 132
ansi_source = "Catppuccin Mocha + Aincrad"
booru = "yuuki_(sao)"
signature = ["cursor", "selection", "ansi13"]

[meta.booru_sites]
konachan = "konno_yuuki"
yande = "konno_yuuki"

[colors]
background = "#1b161d"
foreground = "#eddeef"
cursor = "#7a5a88"
selection_background = "#8f1115"
ansi = [
  "#282229",
  "#ff766c",
  "#52bac5",
  "#f6a98f",
  "#9699e9",
  "#c697c4",
  "#80b7dc",
  "#cec3ce",

  "#7d747e",
  "#edafd4",
  "#93d7e2",
  "#ffd3c7",
  "#babdf5",
  "#dfb9ef",
  "#a7d8fb",
  "#f9e9fa",
]
