[meta]
name = "yuuta"
group = "Chuunibyou"
native = "中二病でも恋がしたい!"
order = 98
ansi_source = "Srcery + Delusion"

[colors]
background = "#1d1512"
foreground = "#fce8c3"
cursor = "#ff5a36"
selection_background = "#3d2119"
ansi = [
  "#241a16",
  "#ef2f27",
  "#519f50",
  "#fbb829",
  "#2c78bf",
  "#e02c6d",
  "#0aaeb3",
  "#baa67f",

  "#918175",
  "#f75341",
  "#98bc37",
  "#fed06e",
  "#68a8e4",
  "#ff5c8f",
  "#2be4d0",
  "#fce8c3",
]
