[meta]
name = "yuuta"
group = "Chuunibyou"
order = 98
ansi_source = "Srcery + Delusion"
signature = ["cursor", "ansi11", "ansi6"]

[colors]
background = "#211512"
foreground = "#fddbd4"
cursor = "#ff5a36"
selection_background = "#55362d"
ansi = [
  "#2e211e",
  "#ff7762",
  "#c3ab1f",
  "#ffa854",
  "#b98de8",
  "#ff7e87",
  "#0aaeb3",
  "#d8c2bd",

  "#85736f",
  "#ffac9d",
  "#fec312",
  "#fed06e",
  "#d3b3ff",
  "#ffb3b6",
  "#bbdf65",
  "#ffe9e5",
]
