import { readFileSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { checkAll } from './contrast.ts'
import { alacritty, type Emitter, ghostty, iterm2, kitty, type Output, wezterm } from './emit/index.ts'
import { loadThemes, rotation, type Theme } from './theme.ts'

const root = join(import.meta.dirname, '..')
const THEMES = join(root, 'themes')
const DIST = join(root, 'dist')

const EMITTERS: Emitter[] = [ghostty, kitty, alacritty, wezterm, iterm2]

export const TERMINALS = EMITTERS.map((e) => e.id)

export interface PaletteEntry {
  name: string
  group: string
  native?: string
  ansiSource: string
  default?: boolean
  background: string
  foreground: string
  cursor: string
  selection: string
  ansi: string[]
}

export function manifest(themes: Theme[]): PaletteEntry[] {
  return themes.map((t) => ({
    name: t.name,
    group: t.group,
    ...(t.native ? { native: t.native } : {}),
    ansiSource: t.ansiSource,
    ...(t.role === 'default' ? { default: true } : {}),
    background: t.background,
    foreground: t.foreground,
    cursor: t.cursor,
    selection: t.selectionBackground,
    ansi: t.ansi,
  }))
}

function shellPalettes(themes: Theme[]): string {
  for (const t of themes) {
    for (const field of [t.name, t.group, t.native ?? '', t.ansiSource]) {
      if (/["$`\\]/.test(field)) {
        throw new Error(`${t.name}: "${field}" contains a character that breaks zsh quoting`)
      }
    }
  }

  const pad = Math.max(...themes.map((t) => t.name.length))
  const entry = (t: Theme, value: string) => `  ${t.name.padEnd(pad)} "${value}"`

  const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

  return [
    '# Generated by `mise run build` — do not edit.',
    '# Source of truth: themes/*.toml in the ttheme repo.',
    '',
    `typeset -g TTHEME_VERSION=${version}`,
    '',
    'typeset -gA TTHEME_PALETTE=(',
    ...themes.map((t) => entry(t, [t.background, t.foreground, t.cursor, t.selectionBackground, ...t.ansi].join(' '))),
    ')',
    '',
    '# display order for `ttheme` and preview — the default role stays applyable but unlisted',
    `typeset -ga TTHEME_ORDER=(${themes
      .filter((t) => t.role !== 'default')
      .map((t) => t.name)
      .join(' ')})`,
    '',
    '# themes new tabs cycle through (the default role sits out)',
    `typeset -ga TTHEME_ROTATION=(${rotation(themes)
      .map((t) => t.name)
      .join(' ')})`,
    '',
    'typeset -gA TTHEME_GROUP=(',
    ...themes.map((t) => entry(t, t.group)),
    ')',
    '',
    '# original-language title, rendered dim next to the group',
    'typeset -gA TTHEME_NATIVE=(',
    ...themes.filter((t) => t.native).map((t) => entry(t, t.native ?? '')),
    ')',
    '',
    "# where each palette's 16 ANSI colors came from",
    'typeset -gA TTHEME_SRC=(',
    ...themes.map((t) => entry(t, t.ansiSource)),
    ')',
    '',
  ].join('\n')
}

export async function build({ only }: { only?: string[] } = {}): Promise<void> {
  if (typeof Bun === 'undefined') {
    throw new Error('ttheme build needs bun — run it from a checkout: bun src/bin.ts build')
  }
  const emitters = only && only.length > 0 ? EMITTERS.filter((e) => only.includes(e.id)) : EMITTERS

  const themes = loadThemes(THEMES)

  const violations = checkAll(themes)
  if (violations.length > 0) {
    for (const v of violations) {
      console.error(`  ✗ ${v.theme} [${v.rule}] ${v.detail}`)
    }
    throw new Error(
      `${violations.length} contrast violation(s). Fix the palette, or waive the rule in its [contrast] section with a reason.`,
    )
  }

  if (emitters.length === EMITTERS.length) {
    rmSync(DIST, { recursive: true, force: true })
  } else {
    for (const e of emitters) {
      rmSync(join(DIST, e.id), { recursive: true, force: true })
    }
  }

  let count = 0
  const write = async (out: Output) => {
    await Bun.write(join(DIST, out.path), out.content)
    count++
  }

  for (const emitter of emitters) {
    for (const theme of themes) {
      for (const out of emitter.emit(theme)) {
        await write(out)
      }
    }
    for (const out of emitter.emitShared?.(themes) ?? []) {
      await write(out)
    }
    console.log(`  ${emitter.id.padEnd(10)} ${themes.length} themes${emitter.limits ? `  (${emitter.limits})` : ''}`)
  }

  await Bun.write(join(DIST, 'shell', 'palettes.zsh'), shellPalettes(themes))
  count++
  console.log(`  ${'shell'.padEnd(10)} palettes.zsh`)

  await Bun.write(join(DIST, 'manifest.json'), JSON.stringify(manifest(themes)))
  count++
  console.log(`  ${'meta'.padEnd(10)} manifest.json`)

  console.log(
    `\n${themes.length} themes (${rotation(themes).length} in the new-tab rotation) -> ${count} files in dist/`,
  )
}
