import pkg from '../../package.json' with { type: 'json' }
import { SITES } from '../booru.ts'
import { HUB_CLOSED, HUB_SWITCH, HUB_TABS } from '../hub.ts'
import { listed, type PaletteEntry, paletteEntry, swatch } from '../manifest.ts'
import { SCENES } from '../scenes.ts'
import { TRAITS } from '../terminal.ts'
import { alphabetical } from '../theme.ts'
import { helpText, VERB_SPECS } from '../verbs.ts'
import { configTemplate, SETTING_NAMES } from '../wiring.ts'
import type { Emitter, Output } from './types.ts'

const UNQUOTABLE = /["$`\\]/

function spoken(tag: string): string {
  return tag.replace(/_\([^)]*\)$/, '').replaceAll('_', ' ')
}

export function palettesZsh(
  palettes: PaletteEntry[],
  startup?: string,
  terminals: readonly string[] = [],
  layer: Readonly<Record<string, string>> = {},
  tuned: readonly string[] = [],
): string {
  for (const p of palettes) {
    for (const field of [p.name, p.group, p.native ?? '', ...(p.nativeNames ?? []), p.ansiSource]) {
      if (UNQUOTABLE.test(field)) {
        throw new Error(`${p.name}: "${field}" contains a character that breaks zsh quoting`)
      }
    }
  }

  const pad = Math.max(0, ...palettes.map((p) => p.name.length))
  const entry = (p: PaletteEntry, value: string) => `  ${p.name.padEnd(pad)} "${value}"`
  const names = (list: PaletteEntry[]) => list.map((p) => p.name).join(' ')
  const rotation = listed(palettes)
  const quote = (text: string) => `'${text.replaceAll("'", "'\\''")}'`
  const verbs = VERB_SPECS.filter((v) => v.section !== 'setup' && !v.hidden)

  return [
    '# Generated by `mise run build` — do not edit.',
    '# Source of truth: themes/*.toml in the ttheme repo.',
    '',
    `typeset -g TTHEME_VERSION=${pkg.version}`,
    '',
    '# the palette new tabs open with, which the iTerm2 "ttheme · default" profile wears',
    `typeset -g TTHEME_STARTUP=${startup ?? ''}`,
    '',
    '# the terminals ttheme is wired into: a picture change reaches every one of them, from whichever runs the shell',
    `typeset -ga TTHEME_TERMINALS=(${terminals.join(' ')})`,
    ...(Object.keys(layer).length > 0
      ? [
          '',
          "# what a wired terminal's adapter needs to know of it (src/terminals/)",
          ...Object.entries(layer).map(([key, value]) => `typeset -g ${key}=${quote(value)}`),
        ]
      : []),
    '',
    '# the commands the shell layer knows (src/verbs.ts): help, completion and argument checks read them',
    `typeset -ga TTHEME_VERBS=(${verbs.map((v) => v.name).join(' ')})`,
    `typeset -ga TTHEME_TAB_VERBS=(${verbs
      .filter((v) => v.section === 'tab')
      .map((v) => v.name)
      .join(' ')})`,
    `typeset -ga TTHEME_SHELL_VERBS=(${verbs
      .filter((v) => v.shell)
      .map((v) => v.name)
      .join(' ')})`,
    'typeset -gA TTHEME_VERB_ARGS=(',
    ...verbs.map((v) => `  ${v.name} ${quote(v.args.join(' '))}`),
    ')',
    'typeset -gA TTHEME_VERB_ABOUT=(',
    ...verbs.map((v) => `  ${v.name} ${quote(v.about)}`),
    ')',
    `typeset -g TTHEME_HELP=${quote(helpText(false, true))}`,
    `typeset -g TTHEME_HELP_ALL=${quote(helpText(true, true))}`,
    '',
    '# the screens the bare ttheme switches between (src/hub.ts): the exit status of a screen run by the CLI says where it went',
    `typeset -ga TTHEME_HUB_TABS=(${HUB_TABS.map((tab) => tab.name).join(' ')})`,
    `typeset -ga TTHEME_HUB_TITLES=(${HUB_TABS.map((tab) => tab.title).join(' ')})`,
    `typeset -gi TTHEME_HUB_CLOSED=${HUB_CLOSED} TTHEME_HUB_SWITCH=${HUB_SWITCH}`,
    '',
    '# the settings config.zsh holds, handed to the CLI on every call',
    `typeset -ga TTHEME_SETTINGS=(${SETTING_NAMES.join(' ')})`,
    '',
    '# seed for `ttheme config` when no config.zsh exists yet',
    `typeset -g TTHEME_CONFIG_TEMPLATE='${configTemplate().trimEnd().replaceAll("'", "'\\''")}'`,
    '',
    'typeset -gA TTHEME_PALETTE=(',
    ...palettes.map((p) => entry(p, [p.background, p.foreground, p.cursor, p.selection, ...p.ansi].join(' '))),
    ')',
    '',
    "# the palettes whose colors your tone moves off their market's (tone.json): lists mark them, and preview's panel offers to reset them",
    `typeset -ga TTHEME_TUNED=(${palettes
      .filter((p) => tuned.includes(p.name))
      .map((p) => p.name)
      .join(' ')})`,
    '',
    '# series order: new tabs cycle through it and TTHEME_SORT=series lists it — the default role stays applyable but unlisted',
    `typeset -ga TTHEME_ORDER=(${names(rotation)})`,
    '',
    '# the same palettes by series name, then palette name: TTHEME_SORT=abc lists them this way',
    `typeset -ga TTHEME_ABC=(${names(alphabetical(rotation))})`,
    '',
    'typeset -gA TTHEME_GROUP=(',
    ...palettes.map((p) => entry(p, p.group)),
    ')',
    '',
    "# the catalog a market palette sits in — the folder under the market's palettes/, one level below the market in every list",
    'typeset -gA TTHEME_CATALOG=(',
    ...palettes.filter((p) => p.catalog).map((p) => entry(p, p.catalog ?? '')),
    ')',
    '',
    '# original-language title, rendered dim next to the group',
    'typeset -gA TTHEME_NATIVE=(',
    ...palettes.filter((p) => p.native).map((p) => entry(p, p.native ?? '')),
    ')',
    '',
    "# the character's names in its original language, |-separated, and as its booru tag spells it: preview searches both",
    'typeset -gA TTHEME_NATIVE_NAMES=(',
    ...palettes.filter((p) => p.nativeNames).map((p) => entry(p, (p.nativeNames ?? []).join('|'))),
    ')',
    'typeset -gA TTHEME_CHARACTER=(',
    ...palettes.filter((p) => p.booru && !UNQUOTABLE.test(p.booru)).map((p) => entry(p, spoken(p.booru ?? ''))),
    ')',
    '',
    '# the example scenes preview draws beside the list (src/scenes.ts), each line as «role»text runs',
    `typeset -ga TTHEME_SCENES=(${SCENES.map((scene) => scene.name).join(' ')})`,
    ...SCENES.flatMap((scene, i) => [
      `typeset -ga TTHEME_SCENE_${i + 1}=(`,
      ...scene.lines.map((line) => `  ${quote(line)}`),
      ')',
    ]),
    '',
    "# each booru's ANSI color, which marks a link to one of its posts",
    `typeset -gA TTHEME_SITE_ANSI=(${SITES.map((site) => `${site.name} ${site.ansi}`).join(' ')})`,
    '',
    '# the terminals that open OSC 8 links (src/terminal.ts)',
    `typeset -ga TTHEME_LINKS=(${Object.entries(TRAITS)
      .flatMap(([terminal, traits]) => (traits.links ? [terminal] : []))
      .join(' ')})`,
    '',
    '# the six colors a list row shows: foreground, the signature, then red and green',
    'typeset -gA TTHEME_SWATCH=(',
    ...palettes.map((p) => entry(p, swatch(p).join(' '))),
    ')',
    '',
    "# where each palette's 16 ANSI colors came from",
    'typeset -gA TTHEME_SRC=(',
    ...palettes.map((p) => entry(p, p.ansiSource)),
    ')',
    '',
  ].join('\n')
}

export function aliasesZsh(aliases: Readonly<Record<string, readonly string[]>>): string {
  const rows = Object.entries(aliases).flatMap(([name, all]) => {
    const names = all.filter((each) => !UNQUOTABLE.test(each) && !each.includes('|'))
    return names.length > 0 && !UNQUOTABLE.test(name) ? [[name, names.join('|')] as const] : []
  })
  const pad = Math.max(0, ...rows.map(([name]) => name.length))
  return [
    "# the character's other names in every language, |-separated, from the aninames index in the cache: preview reads this when it opens and searches them too",
    'typeset -gA TTHEME_ALIASES=(',
    ...rows.map(([name, names]) => `  ${name.padEnd(pad)} "${names}"`),
    ')',
    '',
  ].join('\n')
}

export const shell: Emitter = {
  id: 'shell',

  emitShared(themes): Output[] {
    return [{ path: 'shell/palettes.zsh', content: palettesZsh(themes.map(paletteEntry)) }]
  },
}
