import pkg from '../../package.json' with { type: 'json' }
import { alphabetical } from '../theme.ts'
import { VERB_SPECS } from '../verbs.ts'
import { configTemplate, SETTING_NAMES } from '../wiring.ts'
import type { Emitter, Output } from './index.ts'
import { listed, type PaletteEntry, paletteEntry } from './manifest.ts'

export function palettesZsh(palettes: PaletteEntry[], startup?: string, terminals: readonly string[] = []): string {
  for (const p of palettes) {
    for (const field of [p.name, p.group, p.native ?? '', p.ansiSource]) {
      if (/["$`\\]/.test(field)) {
        throw new Error(`${p.name}: "${field}" contains a character that breaks zsh quoting`)
      }
    }
  }

  const pad = Math.max(0, ...palettes.map((p) => p.name.length))
  const entry = (p: PaletteEntry, value: string) => `  ${p.name.padEnd(pad)} "${value}"`
  const names = (list: PaletteEntry[]) => list.map((p) => p.name).join(' ')
  const rotation = listed(palettes)
  const quote = (text: string) => `'${text.replaceAll("'", "'\\''")}'`
  const verbs = VERB_SPECS.filter((v) => v.section !== 'setup' && !v.hidden)
  const order = verbs.flatMap((v, i) => (i > 0 && verbs[i - 1]?.section !== v.section ? ['-', v.name] : [v.name]))

  return [
    '# Generated by `mise run build` — do not edit.',
    '# Source of truth: themes/*.toml in the ttheme repo.',
    '',
    `typeset -g TTHEME_VERSION=${pkg.version}`,
    '',
    '# the palette new tabs open with, which the iTerm2 "ttheme · default" profile wears',
    `typeset -g TTHEME_STARTUP=${startup ?? ''}`,
    '',
    '# the terminals ttheme is wired into: a picture change reaches every one of them, from whichever runs the shell',
    `typeset -ga TTHEME_TERMINALS=(${terminals.join(' ')})`,
    '',
    '# the commands the shell layer knows (src/verbs.ts): help, completion and argument checks read them',
    `typeset -ga TTHEME_VERBS=(${order.join(' ')})`,
    `typeset -ga TTHEME_SHELL_VERBS=(${verbs
      .filter((v) => v.shell)
      .map((v) => v.name)
      .join(' ')})`,
    'typeset -gA TTHEME_VERB_ARGS=(',
    ...verbs.map((v) => `  ${v.name} ${quote(v.args.join(' '))}`),
    ')',
    'typeset -gA TTHEME_VERB_ABOUT=(',
    ...verbs.map((v) => `  ${v.name} ${quote(v.about)}`),
    ')',
    '',
    '# the settings config.zsh holds, handed to the CLI on every call',
    `typeset -ga TTHEME_SETTINGS=(${SETTING_NAMES.join(' ')})`,
    '',
    '# seed for `ttheme config` when no config.zsh exists yet',
    `typeset -g TTHEME_CONFIG_TEMPLATE='${configTemplate().trimEnd().replaceAll("'", "'\\''")}'`,
    '',
    'typeset -gA TTHEME_PALETTE=(',
    ...palettes.map((p) => entry(p, [p.background, p.foreground, p.cursor, p.selection, ...p.ansi].join(' '))),
    ')',
    '',
    '# series order: new tabs cycle through it and TTHEME_SORT=series lists it — the default role stays applyable but unlisted',
    `typeset -ga TTHEME_ORDER=(${names(rotation)})`,
    '',
    '# the same palettes by series name, then palette name: TTHEME_SORT=abc lists them this way',
    `typeset -ga TTHEME_ABC=(${names(alphabetical(rotation))})`,
    '',
    'typeset -gA TTHEME_GROUP=(',
    ...palettes.map((p) => entry(p, p.group)),
    ')',
    '',
    '# original-language title, rendered dim next to the group',
    'typeset -gA TTHEME_NATIVE=(',
    ...palettes.filter((p) => p.native).map((p) => entry(p, p.native ?? '')),
    ')',
    '',
    "# where each palette's 16 ANSI colors came from",
    'typeset -gA TTHEME_SRC=(',
    ...palettes.map((p) => entry(p, p.ansiSource)),
    ')',
    '',
  ].join('\n')
}

export const shell: Emitter = {
  id: 'shell',

  emitShared(themes): Output[] {
    return [{ path: 'shell/palettes.zsh', content: palettesZsh(themes.map(paletteEntry)) }]
  },
}
