import pkg from '../../package.json' with { type: 'json' }
import { alphabetical, rotation, type Theme } from '../theme.ts'
import { configTemplate } from '../wiring.ts'
import type { Emitter, Output } from './index.ts'

function palettesZsh(themes: Theme[]): string {
  for (const t of themes) {
    for (const field of [t.name, t.group, t.native ?? '', t.ansiSource]) {
      if (/["$`\\]/.test(field)) {
        throw new Error(`${t.name}: "${field}" contains a character that breaks zsh quoting`)
      }
    }
  }

  const pad = Math.max(...themes.map((t) => t.name.length))
  const entry = (t: Theme, value: string) => `  ${t.name.padEnd(pad)} "${value}"`
  const names = (list: Theme[]) => list.map((t) => t.name).join(' ')
  const listed = rotation(themes)

  return [
    '# Generated by `mise run build` — do not edit.',
    '# Source of truth: themes/*.toml in the ttheme repo.',
    '',
    `typeset -g TTHEME_VERSION=${pkg.version}`,
    '',
    '# seed for `ttheme config` when no config.zsh exists yet',
    `typeset -g TTHEME_CONFIG_TEMPLATE='${configTemplate().trimEnd().replaceAll("'", "'\\''")}'`,
    '',
    'typeset -gA TTHEME_PALETTE=(',
    ...themes.map((t) => entry(t, [t.background, t.foreground, t.cursor, t.selectionBackground, ...t.ansi].join(' '))),
    ')',
    '',
    '# series order: new tabs cycle through it and TTHEME_SORT=series lists it — the default role stays applyable but unlisted',
    `typeset -ga TTHEME_ORDER=(${names(listed)})`,
    '',
    '# the same palettes by series name, then palette name: TTHEME_SORT=abc lists them this way',
    `typeset -ga TTHEME_ABC=(${names(alphabetical(listed))})`,
    '',
    'typeset -gA TTHEME_GROUP=(',
    ...themes.map((t) => entry(t, t.group)),
    ')',
    '',
    '# original-language title, rendered dim next to the group',
    'typeset -gA TTHEME_NATIVE=(',
    ...themes.filter((t) => t.native).map((t) => entry(t, t.native ?? '')),
    ')',
    '',
    "# where each palette's 16 ANSI colors came from",
    'typeset -gA TTHEME_SRC=(',
    ...themes.map((t) => entry(t, t.ansiSource)),
    ')',
    '',
  ].join('\n')
}

export const shell: Emitter = {
  id: 'shell',

  emitShared(themes: Theme[]): Output[] {
    return [{ path: 'shell/palettes.zsh', content: palettesZsh(themes) }]
  },
}
